// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SkillGenerator tool
//      Version: 1.0.0.0

//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

using Util;
using System.Collections;
using System.Collections.Generic;
namespace WG
{
   public class SDAchievement : StaticDataBase
   {
       public string Id;
       public string Name;
       public string IconName;
       public string Description;
       public List<string> AwardList;
       public List<int> Detail;
       public string EnterBtn;
        private static string _dataPath = "StaticData/SDAchievement";
       private static Dictionary<string,SDAchievement> _data = new Dictionary<string,SDAchievement>();
       private static List<SDAchievement> _dataList = new List<SDAchievement>();
       public static List<SDAchievement> GetDataList()
       {
           return _dataList;
       }

       public override void LoadData()
       {
           string json = StaticDataLoader.GetText(_dataPath);
           List<SDAchievement> dataList = LitJson.JsonMapper.ToObject<List<SDAchievement>>(json);
           for(int i = 0; i < dataList.Count; i++)
           {
               _data.Add(dataList[i].Id, dataList[i]);
               _dataList.Add(dataList[i]);
           }
       }

       public override void Clear()
       {
           base.Clear();
           _dataList.Clear();
           _data.Clear();
       }

        public static SDAchievement GetElement(string id)
       {
            SDAchievement val = null;
            _data.TryGetValue(id, out val);
            return val;
       }
   }
}
