// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SkillGenerator tool
//      Version: 1.0.0.0

//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

using Util;
using System.Collections;
using System.Collections.Generic;
namespace WG
{
   public class SDAchievementType : StaticDataBase
   {
       public string Id;
       public List<string> Aid;
        private static string _dataPath = "StaticData/SDAchievementType";
       private static Dictionary<string,SDAchievementType> _data = new Dictionary<string,SDAchievementType>();
       private static List<SDAchievementType> _dataList = new List<SDAchievementType>();
       public static List<SDAchievementType> GetDataList()
       {
           return _dataList;
       }

       public override void LoadData()
       {
           string json = StaticDataLoader.GetText(_dataPath);
           List<SDAchievementType> dataList = LitJson.JsonMapper.ToObject<List<SDAchievementType>>(json);
           for(int i = 0; i < dataList.Count; i++)
           {
               _data.Add(dataList[i].Id, dataList[i]);
               _dataList.Add(dataList[i]);
           }
       }

       public override void Clear()
       {
           base.Clear();
           _dataList.Clear();
           _data.Clear();
       }

        public static SDAchievementType GetElement(string id)
       {
            SDAchievementType val = null;
            _data.TryGetValue(id, out val);
            return val;
       }
   }
}
