// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SkillGenerator tool
//      Version: 1.0.0.0

//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

using Util;
using System.Collections;
using System.Collections.Generic;
namespace WG
{
   public class SDAISingleOperation : StaticDataBase
   {
       public string Id;
       public int type;
       public int executeFrame;
       public List<int> paramsList;
        private static string _dataPath = "StaticData/SDAISingleOperation";
       private static Dictionary<string,SDAISingleOperation> _data = new Dictionary<string,SDAISingleOperation>();
       private static List<SDAISingleOperation> _dataList = new List<SDAISingleOperation>();
       public static List<SDAISingleOperation> GetDataList()
       {
           return _dataList;
       }

       public override void LoadData()
       {
           string json = StaticDataLoader.GetText(_dataPath);
           List<SDAISingleOperation> dataList = LitJson.JsonMapper.ToObject<List<SDAISingleOperation>>(json);
           for(int i = 0; i < dataList.Count; i++)
           {
               _data.Add(dataList[i].Id, dataList[i]);
               _dataList.Add(dataList[i]);
           }
       }

       public override void Clear()
       {
           base.Clear();
           _dataList.Clear();
           _data.Clear();
       }

        public static SDAISingleOperation GetElement(string id)
       {
            SDAISingleOperation val = null;
            _data.TryGetValue(id, out val);
            return val;
       }
   }
}
