// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SkillGenerator tool
//      Version: 1.0.0.0

//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

using Util;
using System.Collections;
using System.Collections.Generic;
namespace WG
{
   public class SDAIGuider : StaticDataBase
   {
       public string Id;
       public string UserID;
       public string AIName;
       public List<int> Operation1;
       public List<string> Cards1;
        private static string _dataPath = "StaticData/SDAIGuider";
       private static Dictionary<string,SDAIGuider> _data = new Dictionary<string,SDAIGuider>();
       private static List<SDAIGuider> _dataList = new List<SDAIGuider>();
       public static List<SDAIGuider> GetDataList()
       {
           return _dataList;
       }

       public override void LoadData()
       {
           string json = StaticDataLoader.GetText(_dataPath);
           List<SDAIGuider> dataList = LitJson.JsonMapper.ToObject<List<SDAIGuider>>(json);
           for(int i = 0; i < dataList.Count; i++)
           {
               _data.Add(dataList[i].Id, dataList[i]);
               _dataList.Add(dataList[i]);
           }
       }

       public override void Clear()
       {
           base.Clear();
           _dataList.Clear();
           _data.Clear();
       }

        public static SDAIGuider GetElement(string id)
       {
            SDAIGuider val = null;
            _data.TryGetValue(id, out val);
            return val;
       }
   }
}
