// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SkillGenerator tool
//      Version: 1.0.0.0

//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

using Util;
using System.Collections;
using System.Collections.Generic;
namespace WG
{
   public class SDAIOperations : StaticDataBase
   {
       public string Id;
       public int Seat;
       public List<string> Cards;
       public List<int> Operations;
        private static string _dataPath = "StaticData/SDAIOperations";
       private static Dictionary<string,SDAIOperations> _data = new Dictionary<string,SDAIOperations>();
       private static List<SDAIOperations> _dataList = new List<SDAIOperations>();
       public static List<SDAIOperations> GetDataList()
       {
           return _dataList;
       }

       public override void LoadData()
       {
           string json = StaticDataLoader.GetText(_dataPath);
           List<SDAIOperations> dataList = LitJson.JsonMapper.ToObject<List<SDAIOperations>>(json);
           for(int i = 0; i < dataList.Count; i++)
           {
               _data.Add(dataList[i].Id, dataList[i]);
               _dataList.Add(dataList[i]);
           }
       }

       public override void Clear()
       {
           base.Clear();
           _dataList.Clear();
           _data.Clear();
       }

        public static SDAIOperations GetElement(string id)
       {
            SDAIOperations val = null;
            _data.TryGetValue(id, out val);
            return val;
       }
   }
}
