// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SkillGenerator tool
//      Version: 1.0.0.0

//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

using Util;
using System.Collections;
using System.Collections.Generic;
namespace WG
{
   public class SDAudioResource : StaticDataBase
   {
       public string Id;
       public string Name;
       public string EffectPath;
       public int MaxCount;
        private static string _dataPath = "StaticData/SDAudioResource";
       private static Dictionary<string,SDAudioResource> _data = new Dictionary<string,SDAudioResource>();
       private static List<SDAudioResource> _dataList = new List<SDAudioResource>();
       public static List<SDAudioResource> GetDataList()
       {
           return _dataList;
       }

       public override void LoadData()
       {
           string json = StaticDataLoader.GetText(_dataPath);
           List<SDAudioResource> dataList = LitJson.JsonMapper.ToObject<List<SDAudioResource>>(json);
           for(int i = 0; i < dataList.Count; i++)
           {
               _data.Add(dataList[i].Id, dataList[i]);
               _dataList.Add(dataList[i]);
           }
       }

       public override void Clear()
       {
           base.Clear();
           _dataList.Clear();
           _data.Clear();
       }

        public static SDAudioResource GetElement(string id)
       {
            SDAudioResource val = null;
            _data.TryGetValue(id, out val);
            return val;
       }
   }
}
