// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SkillGenerator tool
//      Version: 1.0.0.0

//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

using Util;
using System.Collections;
using System.Collections.Generic;
namespace WG
{
   public class SDAwardDescription : StaticDataBase
   {
       public string Id;
       public string IconName;
       public string DisplayName;
       public string DisplayDescription;
        private static string _dataPath = "StaticData/SDAwardDescription";
       private static Dictionary<string,SDAwardDescription> _data = new Dictionary<string,SDAwardDescription>();
       private static List<SDAwardDescription> _dataList = new List<SDAwardDescription>();
       public static List<SDAwardDescription> GetDataList()
       {
           return _dataList;
       }

       public override void LoadData()
       {
           string json = StaticDataLoader.GetText(_dataPath);
           List<SDAwardDescription> dataList = LitJson.JsonMapper.ToObject<List<SDAwardDescription>>(json);
           for(int i = 0; i < dataList.Count; i++)
           {
               _data.Add(dataList[i].Id, dataList[i]);
               _dataList.Add(dataList[i]);
           }
       }

       public override void Clear()
       {
           base.Clear();
           _dataList.Clear();
           _data.Clear();
       }

        public static SDAwardDescription GetElement(string id)
       {
            SDAwardDescription val = null;
            _data.TryGetValue(id, out val);
            return val;
       }
   }
}
