// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SkillGenerator tool
//      Version: 1.0.0.0

//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

using Util;
using System.Collections;
using System.Collections.Generic;
namespace WG
{
   public class SDBattleGuide : StaticDataBase
   {
       public string Id;
       public int Frame;
       public string Type;
       public List<string> Params;
        private static string _dataPath = "StaticData/SDBattleGuide";
       private static Dictionary<string,SDBattleGuide> _data = new Dictionary<string,SDBattleGuide>();
       private static List<SDBattleGuide> _dataList = new List<SDBattleGuide>();
       public static List<SDBattleGuide> GetDataList()
       {
           return _dataList;
       }

       public override void LoadData()
       {
           string json = StaticDataLoader.GetText(_dataPath);
           List<SDBattleGuide> dataList = LitJson.JsonMapper.ToObject<List<SDBattleGuide>>(json);
           for(int i = 0; i < dataList.Count; i++)
           {
               _data.Add(dataList[i].Id, dataList[i]);
               _dataList.Add(dataList[i]);
           }
       }

       public override void Clear()
       {
           base.Clear();
           _dataList.Clear();
           _data.Clear();
       }

        public static SDBattleGuide GetElement(string id)
       {
            SDBattleGuide val = null;
            _data.TryGetValue(id, out val);
            return val;
       }
   }
}
