// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SkillGenerator tool
//      Version: 1.0.0.0

//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

using Util;
using System.Collections;
using System.Collections.Generic;
namespace WG
{
   public class SDBattleGuideIndex : StaticDataBase
   {
       public string Id;
       public List<string> paramsList;
        private static string _dataPath = "StaticData/SDBattleGuideIndex";
       private static Dictionary<string,SDBattleGuideIndex> _data = new Dictionary<string,SDBattleGuideIndex>();
       private static List<SDBattleGuideIndex> _dataList = new List<SDBattleGuideIndex>();
       public static List<SDBattleGuideIndex> GetDataList()
       {
           return _dataList;
       }

       public override void LoadData()
       {
           string json = StaticDataLoader.GetText(_dataPath);
           List<SDBattleGuideIndex> dataList = LitJson.JsonMapper.ToObject<List<SDBattleGuideIndex>>(json);
           for(int i = 0; i < dataList.Count; i++)
           {
               _data.Add(dataList[i].Id, dataList[i]);
               _dataList.Add(dataList[i]);
           }
       }

       public override void Clear()
       {
           base.Clear();
           _dataList.Clear();
           _data.Clear();
       }

        public static SDBattleGuideIndex GetElement(string id)
       {
            SDBattleGuideIndex val = null;
            _data.TryGetValue(id, out val);
            return val;
       }
   }
}
