// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SkillGenerator tool
//      Version: 1.0.0.0

//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

using Util;
using System.Collections;
using System.Collections.Generic;
namespace WG
{
   public class SDBox : StaticDataBase
   {
       public string Id;
       public int Bid;
       public int Grade;
       public string Name;
       public string Icon;
       public int GreenHandBox;
       public int OpenTime;
       public int Total;
       public int RareMin;
       public int EpicMin;
       public int LegendMin;
       public int ItemProbability;
       public int NormalItemMax;
       public int RareItemMax;
       public int EpicItemMax;
       public int LegendItemMax;
       public int RareMax;
       public int EpicMax;
       public int LegendMax;
       public int NormalItemMin;
       public int RareItemMin;
       public int EpicItemMin;
       public int LegendItemMin;
       public int RareProbability;
       public int EpicProbability;
       public int LegendProbability;
       public int EpicProbabilityRise;
       public int LegendProbabilityRise;
        private static string _dataPath = "StaticData/SDBox";
       private static Dictionary<string,SDBox> _data = new Dictionary<string,SDBox>();
       private static List<SDBox> _dataList = new List<SDBox>();
       public static List<SDBox> GetDataList()
       {
           return _dataList;
       }

       public override void LoadData()
       {
           string json = StaticDataLoader.GetText(_dataPath);
           List<SDBox> dataList = LitJson.JsonMapper.ToObject<List<SDBox>>(json);
           for(int i = 0; i < dataList.Count; i++)
           {
               _data.Add(dataList[i].Id, dataList[i]);
               _dataList.Add(dataList[i]);
           }
       }

       public override void Clear()
       {
           base.Clear();
           _dataList.Clear();
           _data.Clear();
       }

        public static SDBox GetElement(string id)
       {
            SDBox val = null;
            _data.TryGetValue(id, out val);
            return val;
       }
   }
}
