// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SkillGenerator tool
//      Version: 1.0.0.0

//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

using Util;
using System.Collections;
using System.Collections.Generic;
namespace WG
{
   public class SDBullet : StaticDataBase
   {
       public string Id;
       public string Name;
       public string BulletModelId;
       public int Shadow;
       public int MovePath;
       public FixedNum ColliderRadius;
       public int DestroyDelayTime;
       public int FlightSpeed;
       public int OriginAngle;
       public int DelayTime;
       public string HitEffectId;
       public FixedNum OffsetX;
       public FixedNum OffsetY;
       public FixedNum OffsetZ;
       public string MoveType;
       public FixedNum HeightRatio;
       public FixedNum DistanceRatio;
        private static string _dataPath = "StaticData/SDBullet";
       private static Dictionary<string,SDBullet> _data = new Dictionary<string,SDBullet>();
       private static List<SDBullet> _dataList = new List<SDBullet>();
       public static List<SDBullet> GetDataList()
       {
           return _dataList;
       }

       public override void LoadData()
       {
           string json = StaticDataLoader.GetText(_dataPath);
           List<SDBullet> dataList = LitJson.JsonMapper.ToObject<List<SDBullet>>(json);
           for(int i = 0; i < dataList.Count; i++)
           {
               _data.Add(dataList[i].Id, dataList[i]);
               _dataList.Add(dataList[i]);
           }
       }

       public override void Clear()
       {
           base.Clear();
           _dataList.Clear();
           _data.Clear();
       }

        public static SDBullet GetElement(string id)
       {
            SDBullet val = null;
            _data.TryGetValue(id, out val);
            return val;
       }
   }
}
