// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SkillGenerator tool
//      Version: 1.0.0.0

//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

using Util;
using System.Collections;
using System.Collections.Generic;
namespace WG
{
   public class SDBuff : StaticDataBase
   {
       public string Id;
       public string Description;
       public string BuffIcon;
       public string TriEffect;
       public int DelayTimeSpawn;
       public string ContinueEffect;
       public int DelayTimeDelete;
       public string RemoveEffect;
        private static string _dataPath = "StaticData/SDBuff";
       private static Dictionary<string,SDBuff> _data = new Dictionary<string,SDBuff>();
       private static List<SDBuff> _dataList = new List<SDBuff>();
       public static List<SDBuff> GetDataList()
       {
           return _dataList;
       }

       public override void LoadData()
       {
           string json = StaticDataLoader.GetText(_dataPath);
           List<SDBuff> dataList = LitJson.JsonMapper.ToObject<List<SDBuff>>(json);
           for(int i = 0; i < dataList.Count; i++)
           {
               _data.Add(dataList[i].Id, dataList[i]);
               _dataList.Add(dataList[i]);
           }
       }

       public override void Clear()
       {
           base.Clear();
           _dataList.Clear();
           _data.Clear();
       }

        public static SDBuff GetElement(string id)
       {
            SDBuff val = null;
            _data.TryGetValue(id, out val);
            return val;
       }
   }
}
