// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SkillGenerator tool
//      Version: 1.0.0.0

//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

using Util;
using System.Collections;
using System.Collections.Generic;
namespace WG
{
   public class SDConstant : StaticDataBase
   {
       public string Id;
       public string Value;
        private static string _dataPath = "StaticData/SDConstant";
       private static Dictionary<string,SDConstant> _data = new Dictionary<string,SDConstant>();
       private static List<SDConstant> _dataList = new List<SDConstant>();
       public static List<SDConstant> GetDataList()
       {
           return _dataList;
       }

       public override void LoadData()
       {
           string json = StaticDataLoader.GetText(_dataPath);
           List<SDConstant> dataList = LitJson.JsonMapper.ToObject<List<SDConstant>>(json);
           for(int i = 0; i < dataList.Count; i++)
           {
               _data.Add(dataList[i].Id, dataList[i]);
               _dataList.Add(dataList[i]);
           }
       }

       public override void Clear()
       {
           base.Clear();
           _dataList.Clear();
           _data.Clear();
       }

        public static SDConstant GetElement(string id)
       {
            SDConstant val = null;
            _data.TryGetValue(id, out val);
            return val;
       }
   }
}
