// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SkillGenerator tool
//      Version: 1.0.0.0

//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

using Util;
using System.Collections;
using System.Collections.Generic;
namespace WG
{
   public class SDEffect : StaticDataBase
   {
       public string Id;
       public string Name;
       public int EffectType;
       public string EffectPath;
       public string NodeName;
       public int Par1;
       public int Par2;
       public int Par3;
       public int DirectionMode;
       public int FollowMode;
       public FixedNum Rate;
       public List<string> SDAudioResourceIDList;
       public int SDCameraEffectID;
       public int SDAdvancedEffectID;
       public int Delay;
        private static string _dataPath = "StaticData/SDEffect";
       private static Dictionary<string,SDEffect> _data = new Dictionary<string,SDEffect>();
       private static List<SDEffect> _dataList = new List<SDEffect>();
       public static List<SDEffect> GetDataList()
       {
           return _dataList;
       }

       public override void LoadData()
       {
           string json = StaticDataLoader.GetText(_dataPath);
           List<SDEffect> dataList = LitJson.JsonMapper.ToObject<List<SDEffect>>(json);
           for(int i = 0; i < dataList.Count; i++)
           {
               _data.Add(dataList[i].Id, dataList[i]);
               _dataList.Add(dataList[i]);
           }
       }

       public override void Clear()
       {
           base.Clear();
           _dataList.Clear();
           _data.Clear();
       }

        public static SDEffect GetElement(string id)
       {
            SDEffect val = null;
            _data.TryGetValue(id, out val);
            return val;
       }
   }
}
