// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SkillGenerator tool
//      Version: 1.0.0.0

//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

using Util;
using System.Collections;
using System.Collections.Generic;
namespace WG
{
   public class SDGradeCard : StaticDataBase
   {
       public string Id;
       public string GradeId;
       public List<int> NormalCards;
       public List<int> NormalCardsWeight;
       public List<int> RareCards;
       public List<int> RareCardsWeight;
       public List<int> EpicCards;
       public List<int> EpicCardsWeight;
       public List<int> LegendCards;
       public List<int> LegendCardsWeight;
        private static string _dataPath = "StaticData/SDGradeCard";
       private static Dictionary<string,SDGradeCard> _data = new Dictionary<string,SDGradeCard>();
       private static List<SDGradeCard> _dataList = new List<SDGradeCard>();
       public static List<SDGradeCard> GetDataList()
       {
           return _dataList;
       }

       public override void LoadData()
       {
           string json = StaticDataLoader.GetText(_dataPath);
           List<SDGradeCard> dataList = LitJson.JsonMapper.ToObject<List<SDGradeCard>>(json);
           for(int i = 0; i < dataList.Count; i++)
           {
               _data.Add(dataList[i].Id, dataList[i]);
               _dataList.Add(dataList[i]);
           }
       }

       public override void Clear()
       {
           base.Clear();
           _dataList.Clear();
           _data.Clear();
       }

        public static SDGradeCard GetElement(string id)
       {
            SDGradeCard val = null;
            _data.TryGetValue(id, out val);
            return val;
       }
   }
}
