// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SkillGenerator tool
//      Version: 1.0.0.0

//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

using Util;
using System.Collections;
using System.Collections.Generic;
namespace WG
{
   public class SDGrade : StaticDataBase
   {
       public string Id;
       public string BattleGrade;
       public string SceneName;
       public string IconName;
       public string Name;
       public int MinScoreRead;
       public int MinScore;
       public int MaxScore;
       public int GoldAward;
       public string GradeIcon;
       public string GradeName;
        private static string _dataPath = "StaticData/SDGrade";
       private static Dictionary<string,SDGrade> _data = new Dictionary<string,SDGrade>();
       private static List<SDGrade> _dataList = new List<SDGrade>();
       public static List<SDGrade> GetDataList()
       {
           return _dataList;
       }

       public override void LoadData()
       {
           string json = StaticDataLoader.GetText(_dataPath);
           List<SDGrade> dataList = LitJson.JsonMapper.ToObject<List<SDGrade>>(json);
           for(int i = 0; i < dataList.Count; i++)
           {
               _data.Add(dataList[i].Id, dataList[i]);
               _dataList.Add(dataList[i]);
           }
       }

       public override void Clear()
       {
           base.Clear();
           _dataList.Clear();
           _data.Clear();
       }

        public static SDGrade GetElement(string id)
       {
            SDGrade val = null;
            _data.TryGetValue(id, out val);
            return val;
       }
   }
}
