// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SkillGenerator tool
//      Version: 1.0.0.0

//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

using Util;
using System.Collections;
using System.Collections.Generic;
namespace WG
{
   public class SDGuide : StaticDataBase
   {
       public string Id;
       public string GuideType;
       public string GuideName;
       public List<string> paramsList;
        private static string _dataPath = "StaticData/SDGuide";
       private static Dictionary<string,SDGuide> _data = new Dictionary<string,SDGuide>();
       private static List<SDGuide> _dataList = new List<SDGuide>();
       public static List<SDGuide> GetDataList()
       {
           return _dataList;
       }

       public override void LoadData()
       {
           string json = StaticDataLoader.GetText(_dataPath);
           List<SDGuide> dataList = LitJson.JsonMapper.ToObject<List<SDGuide>>(json);
           for(int i = 0; i < dataList.Count; i++)
           {
               _data.Add(dataList[i].Id, dataList[i]);
               _dataList.Add(dataList[i]);
           }
       }

       public override void Clear()
       {
           base.Clear();
           _dataList.Clear();
           _data.Clear();
       }

        public static SDGuide GetElement(string id)
       {
            SDGuide val = null;
            _data.TryGetValue(id, out val);
            return val;
       }
   }
}
