// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SkillGenerator tool
//      Version: 1.0.0.0

//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

using Util;
using System.Collections;
using System.Collections.Generic;
namespace WG
{
   public class SDGuideClickBtn : StaticDataBase
   {
       public string Id;
       public string PanelName;
       public string BtnName;
       public string Tips;
       public List<int> TipsOffset;
       public List<string> Dialogue;
        private static string _dataPath = "StaticData/SDGuideClickBtn";
       private static Dictionary<string,SDGuideClickBtn> _data = new Dictionary<string,SDGuideClickBtn>();
       private static List<SDGuideClickBtn> _dataList = new List<SDGuideClickBtn>();
       public static List<SDGuideClickBtn> GetDataList()
       {
           return _dataList;
       }

       public override void LoadData()
       {
           string json = StaticDataLoader.GetText(_dataPath);
           List<SDGuideClickBtn> dataList = LitJson.JsonMapper.ToObject<List<SDGuideClickBtn>>(json);
           for(int i = 0; i < dataList.Count; i++)
           {
               _data.Add(dataList[i].Id, dataList[i]);
               _dataList.Add(dataList[i]);
           }
       }

       public override void Clear()
       {
           base.Clear();
           _dataList.Clear();
           _data.Clear();
       }

        public static SDGuideClickBtn GetElement(string id)
       {
            SDGuideClickBtn val = null;
            _data.TryGetValue(id, out val);
            return val;
       }
   }
}
