// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SkillGenerator tool
//      Version: 1.0.0.0

//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

using Util;
using System.Collections;
using System.Collections.Generic;
namespace WG
{
   public class SDHeroCard : StaticDataBase
   {
       public string Id;
       public int AttackBase;
       public string AttackType;
       public FixedNum AttackDistance;
       public int AttackCd;
       public int ArmorValue;
       public string ArmorType;
       public int HpFull;
       public string SkillId;
       public int WalkSpeed;
       public int BasicCard;
       public int Cost;
       public string PrefabName;
       public int ColliderSize;
       public string BulletId;
       public int Seat;
       public int BreakDamage;
       public int BreakAward;
       public int KilledAward;
       public int ManaFull;
       public int ManaRecoveryRate;
       public List<string> CidAdvanceUnlock;
       public List<string> CidAdvanceLock;
       public string CardType;
       public string SpawnEffectID;
       public string DeadEffectID;
       public string AvatorConfig;
       public string Species;
       public string BranchType;
       public List<string> BranchCardID;
       public int Lansquenet;
        private static string _dataPath = "StaticData/SDHeroCard";
       private static Dictionary<string,SDHeroCard> _data = new Dictionary<string,SDHeroCard>();
       private static List<SDHeroCard> _dataList = new List<SDHeroCard>();
       public static List<SDHeroCard> GetDataList()
       {
           return _dataList;
       }

       public override void LoadData()
       {
           string json = StaticDataLoader.GetText(_dataPath);
           List<SDHeroCard> dataList = LitJson.JsonMapper.ToObject<List<SDHeroCard>>(json);
           for(int i = 0; i < dataList.Count; i++)
           {
               _data.Add(dataList[i].Id, dataList[i]);
               _dataList.Add(dataList[i]);
           }
       }

       public override void Clear()
       {
           base.Clear();
           _dataList.Clear();
           _data.Clear();
       }

        public static SDHeroCard GetElement(string id)
       {
            SDHeroCard val = null;
            _data.TryGetValue(id, out val);
            return val;
       }
   }
}
