// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SkillGenerator tool
//      Version: 1.0.0.0

//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

using Util;
using System.Collections;
using System.Collections.Generic;
namespace WG
{
   public class SDIPConfig : StaticDataBase
   {
       public string Id;
       public string PomeloIP;
       public int PomeloPort;
       public string HttpIP;
       public int HttpPort;
       public string ForumGetIP;
       public int ForumGetPort;
       public string ForumPostIP;
       public int ForumPostPort;
        private static string _dataPath = "StaticData/SDIPConfig";
       private static Dictionary<string,SDIPConfig> _data = new Dictionary<string,SDIPConfig>();
       private static List<SDIPConfig> _dataList = new List<SDIPConfig>();
       public static List<SDIPConfig> GetDataList()
       {
           return _dataList;
       }

       public override void LoadData()
       {
           string json = StaticDataLoader.GetText(_dataPath);
           List<SDIPConfig> dataList = LitJson.JsonMapper.ToObject<List<SDIPConfig>>(json);
           for(int i = 0; i < dataList.Count; i++)
           {
               _data.Add(dataList[i].Id, dataList[i]);
               _dataList.Add(dataList[i]);
           }
       }

       public override void Clear()
       {
           base.Clear();
           _dataList.Clear();
           _data.Clear();
       }

        public static SDIPConfig GetElement(string id)
       {
            SDIPConfig val = null;
            _data.TryGetValue(id, out val);
            return val;
       }
   }
}
