// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SkillGenerator tool
//      Version: 1.0.0.0

//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

using Util;
using System.Collections;
using System.Collections.Generic;
namespace WG
{
   public class SDMission : StaticDataBase
   {
       public string Id;
       public string Name;
       public string IconName;
       public string Description;
       public List<string> AwardList;
       public List<int> Detail;
       public string EnterBtn;
        private static string _dataPath = "StaticData/SDMission";
       private static Dictionary<string,SDMission> _data = new Dictionary<string,SDMission>();
       private static List<SDMission> _dataList = new List<SDMission>();
       public static List<SDMission> GetDataList()
       {
           return _dataList;
       }

       public override void LoadData()
       {
           string json = StaticDataLoader.GetText(_dataPath);
           List<SDMission> dataList = LitJson.JsonMapper.ToObject<List<SDMission>>(json);
           for(int i = 0; i < dataList.Count; i++)
           {
               _data.Add(dataList[i].Id, dataList[i]);
               _dataList.Add(dataList[i]);
           }
       }

       public override void Clear()
       {
           base.Clear();
           _dataList.Clear();
           _data.Clear();
       }

        public static SDMission GetElement(string id)
       {
            SDMission val = null;
            _data.TryGetValue(id, out val);
            return val;
       }
   }
}
