// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SkillGenerator tool
//      Version: 1.0.0.0

//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

using Util;
using System.Collections;
using System.Collections.Generic;
namespace WG
{
   public class SDShopJewel : StaticDataBase
   {
       public string Id;
       public string ValueRMB;
       public int JewelOutput;
       public string IconName;
       public string Description;
       public string ItunesId;
        private static string _dataPath = "StaticData/SDShopJewel";
       private static Dictionary<string,SDShopJewel> _data = new Dictionary<string,SDShopJewel>();
       private static List<SDShopJewel> _dataList = new List<SDShopJewel>();
       public static List<SDShopJewel> GetDataList()
       {
           return _dataList;
       }

       public override void LoadData()
       {
           string json = StaticDataLoader.GetText(_dataPath);
           List<SDShopJewel> dataList = LitJson.JsonMapper.ToObject<List<SDShopJewel>>(json);
           for(int i = 0; i < dataList.Count; i++)
           {
               _data.Add(dataList[i].Id, dataList[i]);
               _dataList.Add(dataList[i]);
           }
       }

       public override void Clear()
       {
           base.Clear();
           _dataList.Clear();
           _data.Clear();
       }

        public static SDShopJewel GetElement(string id)
       {
            SDShopJewel val = null;
            _data.TryGetValue(id, out val);
            return val;
       }
   }
}
