// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SkillGenerator tool
//      Version: 1.0.0.0

//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

using Util;
using System.Collections;
using System.Collections.Generic;
namespace WG
{
   public class SDShopGold : StaticDataBase
   {
       public string Id;
       public string ValueJewel;
       public int GoldOutput;
       public string IconName;
       public string Description;
        private static string _dataPath = "StaticData/SDShopGold";
       private static Dictionary<string,SDShopGold> _data = new Dictionary<string,SDShopGold>();
       private static List<SDShopGold> _dataList = new List<SDShopGold>();
       public static List<SDShopGold> GetDataList()
       {
           return _dataList;
       }

       public override void LoadData()
       {
           string json = StaticDataLoader.GetText(_dataPath);
           List<SDShopGold> dataList = LitJson.JsonMapper.ToObject<List<SDShopGold>>(json);
           for(int i = 0; i < dataList.Count; i++)
           {
               _data.Add(dataList[i].Id, dataList[i]);
               _dataList.Add(dataList[i]);
           }
       }

       public override void Clear()
       {
           base.Clear();
           _dataList.Clear();
           _data.Clear();
       }

        public static SDShopGold GetElement(string id)
       {
            SDShopGold val = null;
            _data.TryGetValue(id, out val);
            return val;
       }
   }
}
