// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SkillGenerator tool
//      Version: 1.0.0.0

//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

using Util;
using System.Collections;
using System.Collections.Generic;
namespace WG
{
   public class SDStaticDataConfig : StaticDataBase
   {
       public string Id;
        private static string _dataPath = "StaticData/SDStaticDataConfig";
       private static Dictionary<string,SDStaticDataConfig> _data = new Dictionary<string,SDStaticDataConfig>();
       private static List<SDStaticDataConfig> _dataList = new List<SDStaticDataConfig>();
       public static List<SDStaticDataConfig> GetDataList()
       {
           return _dataList;
       }

       public override void LoadData()
       {
           string json = StaticDataLoader.GetText(_dataPath);
           List<SDStaticDataConfig> dataList = LitJson.JsonMapper.ToObject<List<SDStaticDataConfig>>(json);
           for(int i = 0; i < dataList.Count; i++)
           {
               _data.Add(dataList[i].Id, dataList[i]);
               _dataList.Add(dataList[i]);
           }
       }

       public override void Clear()
       {
           base.Clear();
           _dataList.Clear();
           _data.Clear();
       }

        public static SDStaticDataConfig GetElement(string id)
       {
            SDStaticDataConfig val = null;
            _data.TryGetValue(id, out val);
            return val;
       }
   }
}
