// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SkillGenerator tool
//      Version: 1.0.0.0

//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

using Util;
using System.Collections;
using System.Collections.Generic;
namespace WG
{
   public class SDText : StaticDataBase
   {
       public string Id;
       public string ZH_CN;
       public string ZH_TW;
       public string EN;
        private static string _dataPath = "StaticData/SDText";
       private static Dictionary<string,SDText> _data = new Dictionary<string,SDText>();
       private static List<SDText> _dataList = new List<SDText>();
       public static List<SDText> GetDataList()
       {
           return _dataList;
       }

       public override void LoadData()
       {
           string json = StaticDataLoader.GetText(_dataPath);
           List<SDText> dataList = LitJson.JsonMapper.ToObject<List<SDText>>(json);
           for(int i = 0; i < dataList.Count; i++)
           {
               _data.Add(dataList[i].Id, dataList[i]);
               _dataList.Add(dataList[i]);
           }
       }

       public override void Clear()
       {
           base.Clear();
           _dataList.Clear();
           _data.Clear();
       }

        public static SDText GetElement(string id)
       {
            SDText val = null;
            _data.TryGetValue(id, out val);
            return val;
       }
   }
}
