// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SkillGenerator tool
//      Version: 1.0.0.0

//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

using Util;
using System.Collections;
using System.Collections.Generic;
namespace WG
{
   public class SDTips : StaticDataBase
   {
       public string Id;
       public List<string> Tips;
        private static string _dataPath = "StaticData/SDTips";
       private static Dictionary<string,SDTips> _data = new Dictionary<string,SDTips>();
       private static List<SDTips> _dataList = new List<SDTips>();
       public static List<SDTips> GetDataList()
       {
           return _dataList;
       }

       public override void LoadData()
       {
           string json = StaticDataLoader.GetText(_dataPath);
           List<SDTips> dataList = LitJson.JsonMapper.ToObject<List<SDTips>>(json);
           for(int i = 0; i < dataList.Count; i++)
           {
               _data.Add(dataList[i].Id, dataList[i]);
               _dataList.Add(dataList[i]);
           }
       }

       public override void Clear()
       {
           base.Clear();
           _dataList.Clear();
           _data.Clear();
       }

        public static SDTips GetElement(string id)
       {
            SDTips val = null;
            _data.TryGetValue(id, out val);
            return val;
       }
   }
}
