// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SkillGenerator tool
//      Version: 1.0.0.0

//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

using Util;
using System.Collections;
using System.Collections.Generic;
namespace WG
{
   public class SDTowerWave : StaticDataBase
   {
       public string Id;
       public string Difficulty;
       public string WaveId;
       public string SpawnCardID;
       public int SpawnCount;
       public int CountPerFrame;
       public int SpwanTimeInterval;
       public List<int> SpawnPosition;
       public int AwardGoldProbability;
       public int AwardGold;
       public int AwardJewelProbability;
       public int AwardJewel;
       public int RandomCardCount;
       public List<string> RandomCardID;
        private static string _dataPath = "StaticData/SDTowerWave";
       private static Dictionary<string,SDTowerWave> _data = new Dictionary<string,SDTowerWave>();
       private static List<SDTowerWave> _dataList = new List<SDTowerWave>();
       public static List<SDTowerWave> GetDataList()
       {
           return _dataList;
       }

       public override void LoadData()
       {
           string json = StaticDataLoader.GetText(_dataPath);
           List<SDTowerWave> dataList = LitJson.JsonMapper.ToObject<List<SDTowerWave>>(json);
           for(int i = 0; i < dataList.Count; i++)
           {
               _data.Add(dataList[i].Id, dataList[i]);
               _dataList.Add(dataList[i]);
           }
       }

       public override void Clear()
       {
           base.Clear();
           _dataList.Clear();
           _data.Clear();
       }

        public static SDTowerWave GetElement(string id)
       {
            SDTowerWave val = null;
            _data.TryGetValue(id, out val);
            return val;
       }
   }
}
