// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SkillGenerator tool
//      Version: 1.0.0.0

//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

using Util;
using System.Collections;
using System.Collections.Generic;
namespace WG
{
   public class SDUIConfig : StaticDataBase
   {
       public string Id;
       public List<string> AllCardsId;
       public List<string> AllSkillCardsId;
       public string LoginTheme;
       public List<string> MainTheme;
       public int RefreshTime;
       public int RotationRate;
       public string CardInfoEffect;
       public string BattleArrayEffect;
        private static string _dataPath = "StaticData/SDUIConfig";
       private static Dictionary<string,SDUIConfig> _data = new Dictionary<string,SDUIConfig>();
       private static List<SDUIConfig> _dataList = new List<SDUIConfig>();
       public static List<SDUIConfig> GetDataList()
       {
           return _dataList;
       }

       public override void LoadData()
       {
           string json = StaticDataLoader.GetText(_dataPath);
           List<SDUIConfig> dataList = LitJson.JsonMapper.ToObject<List<SDUIConfig>>(json);
           for(int i = 0; i < dataList.Count; i++)
           {
               _data.Add(dataList[i].Id, dataList[i]);
               _dataList.Add(dataList[i]);
           }
       }

       public override void Clear()
       {
           base.Clear();
           _dataList.Clear();
           _data.Clear();
       }

        public static SDUIConfig GetElement(string id)
       {
            SDUIConfig val = null;
            _data.TryGetValue(id, out val);
            return val;
       }
   }
}
