// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SkillGenerator tool
//      Version: 1.0.0.0

//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

using Util;
using System.Collections;
using System.Collections.Generic;
namespace WG
{
   public class SDVirusType : StaticDataBase
   {
       public string Id;
       public List<string> Aid;
        private static string _dataPath = "StaticData/SDVirusType";
       private static Dictionary<string,SDVirusType> _data = new Dictionary<string,SDVirusType>();
       private static List<SDVirusType> _dataList = new List<SDVirusType>();
       public static List<SDVirusType> GetDataList()
       {
           return _dataList;
       }

       public override void LoadData()
       {
           string json = StaticDataLoader.GetText(_dataPath);
           List<SDVirusType> dataList = LitJson.JsonMapper.ToObject<List<SDVirusType>>(json);
           for(int i = 0; i < dataList.Count; i++)
           {
               _data.Add(dataList[i].Id, dataList[i]);
               _dataList.Add(dataList[i]);
           }
       }

       public override void Clear()
       {
           base.Clear();
           _dataList.Clear();
           _data.Clear();
       }

        public static SDVirusType GetElement(string id)
       {
            SDVirusType val = null;
            _data.TryGetValue(id, out val);
            return val;
       }
   }
}
