// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by ProtocalGenerator tool
//      Version: 1.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace Protocol
{

    public static class EncryptionConfig
    {
public static readonly Boolean USE_ENCRYPT_PROTOCOL = true;
public static readonly Boolean USE_ENCRYPT_REQUEST = true;
public static readonly Boolean USE_ENCRYPT_RESPONSE = true;
public static readonly Boolean USE_ENCRYPT_PUSH = true;
public static readonly String GUESS_KEY = "kingduel3016";
public static readonly Dictionary<string, string[]> ENCRYPT_INFO = new Dictionary<string, string[]>() {
            {
                "Protocol.ServerInterFace+Relation+RelationHandler+Chat",
                new string[]
                {
                    "content"
                }
            },
            };
public static readonly Dictionary<string, string[]> PUSH_ENCRYPT_INFO = new Dictionary<string, string[]>() {
            {
                "Protocol.ServerPushInterface+OnAllPlayersReady",
                new string[]
                {
                    "playerInfoList.nickname","playerInfoList.cardIds","playerInfoList.battleCardGroup"
                }
            },
            {
                "Protocol.ServerPushInterface+OnGameOver",
                new string[]
                {
                    "fightAreaName"
                }
            },
            {
                "Protocol.ServerPushInterface+OnMatched",
                new string[]
                {
                    "fightAreaName"
                }
            },
            {
                "Protocol.ServerPushInterface+OnChat",
                new string[]
                {
                    "content"
                }
            },
            };
    }

}
