// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by ProtocalGenerator tool
//      Version: 1.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace Protocol
{

    public class ServerInterFace
    {
        public partial class Gate
        {
            public partial class GateHandler
            {
                public class GetGameConnector : SimonMsg
                {
                    public static string InterfaceName = "gate.gateHandler.getGameConnector";

                    public string numberID;

                    public GetGameConnector(string numberID)
                    {
                        this.numberID = numberID;
                    }


                }
            }
        }
        public partial class Gate
        {
            public partial class GateHandler
            {
                public class GetSceneConnector : SimonMsg
                {
                    public static string InterfaceName = "gate.gateHandler.getSceneConnector";

                    public string region;

                    public GetSceneConnector(string region)
                    {
                        this.region = region;
                    }


                }
            }
        }
        public partial class GameConnector
        {
            public partial class EntryHandler
            {
                public class EnterMatchQueue : SimonMsg
                {
                    public static string InterfaceName = "gameConnector.entryHandler.enterMatchQueue";

                    public int numberID;

                    public int gameMode;

                    public EnterMatchQueue(int numberID,int gameMode)
                    {
                        this.numberID = numberID;
                        this.gameMode = gameMode;
                    }


                }
            }
        }
        public partial class GameConnector
        {
            public partial class EntryHandler
            {
                public class ReconnectFightArea : SimonMsg
                {
                    public static string InterfaceName = "gameConnector.entryHandler.reconnectFightArea";

                    public int numberID;

                    public ReconnectFightArea(int numberID)
                    {
                        this.numberID = numberID;
                    }


                }
            }
        }
        public partial class GameConnector
        {
            public partial class EntryHandler
            {
                public class EnterFightAreaAfterInvited : SimonMsg
                {
                    public static string InterfaceName = "gameConnector.entryHandler.enterFightAreaAfterInvited";

                    public int numberID;

                    public EnterFightAreaAfterInvited(int numberID)
                    {
                        this.numberID = numberID;
                    }


                }
            }
        }
        public partial class Fight
        {
            public partial class FightHandler
            {
                public class Fight : SimonMsg
                {
                    public static string InterfaceName = "fight.fightHandler.fight";

                    public int expectedExecuteFrame;

                    public int type;

                    public List<int> paramsList;

                    public Fight(int expectedExecuteFrame,int type,List<int> paramsList)
                    {
                        this.expectedExecuteFrame = expectedExecuteFrame;
                        this.type = type;
                        this.paramsList = paramsList;
                    }


                }
            }
        }
        public partial class Fight
        {
            public partial class FightHandler
            {
                public class Ready : SimonMsg
                {
                    public static string InterfaceName = "fight.fightHandler.ready";



                }
            }
        }
        public partial class Fight
        {
            public partial class FightHandler
            {
                public class StartFight : SimonMsg
                {
                    public static string InterfaceName = "fight.fightHandler.startFight";



                }
            }
        }
        public partial class Fight
        {
            public partial class FightHandler
            {
                public class GetActionsHistory : SimonMsg
                {
                    public static string InterfaceName = "fight.fightHandler.getActionsHistory";



                }
            }
        }
        public partial class Fight
        {
            public partial class FightHandler
            {
                public class RecallOnAllPlayersReadyMessage : SimonMsg
                {
                    public static string InterfaceName = "fight.fightHandler.recallOnAllPlayersReadyMessage";



                }
            }
        }
        public partial class Fight
        {
            public partial class FightHandler
            {
                public class EndFight : SimonMsg
                {
                    public static string InterfaceName = "fight.fightHandler.endFight";

                    public int gameResult;

                    public EndFight(int gameResult)
                    {
                        this.gameResult = gameResult;
                    }


                }
            }
        }
        public partial class Match
        {
            public partial class MatchHandler
            {
                public class CancelMatch : SimonMsg
                {
                    public static string InterfaceName = "match.matchHandler.cancelMatch";



                }
            }
        }
        public partial class Scene
        {
            public partial class FriendHandler
            {
                public class SendFriendGameInvitation : SimonMsg
                {
                    public static string InterfaceName = "scene.friendHandler.sendFriendGameInvitation";

                    public int gameMode;

                    public int inviteeNumberID;

                    public SendFriendGameInvitation(int gameMode,int inviteeNumberID)
                    {
                        this.gameMode = gameMode;
                        this.inviteeNumberID = inviteeNumberID;
                    }


                }
            }
        }
        public partial class Scene
        {
            public partial class FriendHandler
            {
                public class CancelFriendGameInvitation : SimonMsg
                {
                    public static string InterfaceName = "scene.friendHandler.cancelFriendGameInvitation";



                }
            }
        }
        public partial class Scene
        {
            public partial class FriendHandler
            {
                public class ReplyFriendGameInvitation : SimonMsg
                {
                    public static string InterfaceName = "scene.friendHandler.replyFriendGameInvitation";

                    public int accept;

                    public ReplyFriendGameInvitation(int accept)
                    {
                        this.accept = accept;
                    }


                }
            }
        }
        public partial class Scene
        {
            public partial class FriendHandler
            {
                public class Chat : SimonMsg
                {
                    public static string InterfaceName = "scene.friendHandler.chat";

                    public string content;

                    public int targetNumberID;

                    public Chat(string content,int targetNumberID)
                    {
                        this.content = content;
                        this.targetNumberID = targetNumberID;
                    }


                }
            }
        }
        public partial class Scene
        {
            public partial class FriendHandler
            {
                public class InitFriendsList : SimonMsg
                {
                    public static string InterfaceName = "scene.friendHandler.initFriendsList";



                }
            }
        }
        public partial class Scene
        {
            public partial class FriendHandler
            {
                public class SendAddFriendMsg : SimonMsg
                {
                    public static string InterfaceName = "scene.friendHandler.sendAddFriendMsg";

                    public int inviteeNumberID;

                    public SendAddFriendMsg(int inviteeNumberID)
                    {
                        this.inviteeNumberID = inviteeNumberID;
                    }


                }
            }
        }
        public partial class Scene
        {
            public partial class FriendHandler
            {
                public class ReplyAddFriendInvitation : SimonMsg
                {
                    public static string InterfaceName = "scene.friendHandler.replyAddFriendInvitation";

                    public int inviterNumberID;

                    public int isAgree;

                    public ReplyAddFriendInvitation(int inviterNumberID,int isAgree)
                    {
                        this.inviterNumberID = inviterNumberID;
                        this.isAgree = isAgree;
                    }


                }
            }
        }
        public partial class SceneConnector
        {
            public partial class UserHandler
            {
                public class Login : SimonMsg
                {
                    public static string InterfaceName = "sceneConnector.userHandler.login";

                    public string username;

                    public string password;

                    public string platform;

                    public Login(string username,string password,string platform)
                    {
                        this.username = username;
                        this.password = password;
                        this.platform = platform;
                    }


                }
            }
        }
        public partial class SceneConnector
        {
            public partial class UserHandler
            {
                public class Register : SimonMsg
                {
                    public static string InterfaceName = "sceneConnector.userHandler.register";

                    public string username;

                    public string password;

                    public string region;

                    public string cFrom;

                    public Register(string username,string password,string region,string cFrom)
                    {
                        this.username = username;
                        this.password = password;
                        this.region = region;
                        this.cFrom = cFrom;
                    }


                }
            }
        }
        public partial class SceneConnector
        {
            public partial class UserHandler
            {
                public class UserDetail : SimonMsg
                {
                    public static string InterfaceName = "sceneConnector.userHandler.userDetail";

                    public int numberID;

                    public UserDetail(int numberID)
                    {
                        this.numberID = numberID;
                    }


                }
            }
        }
        public partial class SceneConnector
        {
            public partial class UserHandler
            {
                public class UpdateNickname : SimonMsg
                {
                    public static string InterfaceName = "sceneConnector.userHandler.updateNickname";

                    public string nickname;

                    public UpdateNickname(string nickname)
                    {
                        this.nickname = nickname;
                    }


                }
            }
        }
        public partial class SceneConnector
        {
            public partial class UserHandler
            {
                public class UpdatePortrait : SimonMsg
                {
                    public static string InterfaceName = "sceneConnector.userHandler.updatePortrait";

                    public int portrait;

                    public UpdatePortrait(int portrait)
                    {
                        this.portrait = portrait;
                    }


                }
            }
        }
        public partial class SceneConnector
        {
            public partial class GuideHandler
            {
                public class FinishGuideStep : SimonMsg
                {
                    public static string InterfaceName = "sceneConnector.guideHandler.finishGuideStep";

                    public int step;

                    public FinishGuideStep(int step)
                    {
                        this.step = step;
                    }


                }
            }
        }
        public partial class SceneConnector
        {
            public partial class TrainingHandler
            {
                public class FinishTrainingStep : SimonMsg
                {
                    public static string InterfaceName = "sceneConnector.trainingHandler.finishTrainingStep";

                    public int step;

                    public FinishTrainingStep(int step)
                    {
                        this.step = step;
                    }


                }
            }
        }
        public partial class SceneConnector
        {
            public partial class FriendHandler
            {
                public class Search : SimonMsg
                {
                    public static string InterfaceName = "sceneConnector.friendHandler.search";

                    public string input;

                    public Search(string input)
                    {
                        this.input = input;
                    }


                }
            }
        }
        public partial class SceneConnector
        {
            public partial class ShopHandler
            {
                public class GetShopList : SimonMsg
                {
                    public static string InterfaceName = "sceneConnector.shopHandler.getShopList";



                }
            }
        }
        public partial class SceneConnector
        {
            public partial class ShopHandler
            {
                public class RefreshSellCardList : SimonMsg
                {
                    public static string InterfaceName = "sceneConnector.shopHandler.refreshSellCardList";



                }
            }
        }
        public partial class SceneConnector
        {
            public partial class ShopHandler
            {
                public class BuyShopCard : SimonMsg
                {
                    public static string InterfaceName = "sceneConnector.shopHandler.buyShopCard";

                    public int cardId;

                    public int count;

                    public BuyShopCard(int cardId,int count)
                    {
                        this.cardId = cardId;
                        this.count = count;
                    }


                }
            }
        }
        public partial class SceneConnector
        {
            public partial class ShopHandler
            {
                public class BuyShopBox : SimonMsg
                {
                    public static string InterfaceName = "sceneConnector.shopHandler.buyShopBox";

                    public int boxId;

                    public BuyShopBox(int boxId)
                    {
                        this.boxId = boxId;
                    }


                }
            }
        }
        public partial class SceneConnector
        {
            public partial class ShopHandler
            {
                public class BuyShopGold : SimonMsg
                {
                    public static string InterfaceName = "sceneConnector.shopHandler.buyShopGold";

                    public int goldOutput;

                    public BuyShopGold(int goldOutput)
                    {
                        this.goldOutput = goldOutput;
                    }


                }
            }
        }
        public partial class SceneConnector
        {
            public partial class ShopHandler
            {
                public class BuyShopJewel : SimonMsg
                {
                    public static string InterfaceName = "sceneConnector.shopHandler.buyShopJewel";

                    public string purchaseReceipt;

                    public string clientNeededIndex;

                    public BuyShopJewel(string purchaseReceipt,string clientNeededIndex)
                    {
                        this.purchaseReceipt = purchaseReceipt;
                        this.clientNeededIndex = clientNeededIndex;
                    }


                }
            }
        }
        public partial class SceneConnector
        {
            public partial class TavernHandler
            {
                public class GetList : SimonMsg
                {
                    public static string InterfaceName = "sceneConnector.tavernHandler.getList";



                }
            }
        }
        public partial class SceneConnector
        {
            public partial class TavernHandler
            {
                public class Recruit : SimonMsg
                {
                    public static string InterfaceName = "sceneConnector.tavernHandler.recruit";

                    public int type;

                    public Recruit(int type)
                    {
                        this.type = type;
                    }


                }
            }
        }
        public partial class SceneConnector
        {
            public partial class SignInHandler
            {
                public class GetList : SimonMsg
                {
                    public static string InterfaceName = "sceneConnector.signInHandler.getList";



                }
            }
        }
        public partial class SceneConnector
        {
            public partial class SignInHandler
            {
                public class SignInToday : SimonMsg
                {
                    public static string InterfaceName = "sceneConnector.signInHandler.signInToday";



                }
            }
        }
        public partial class SceneConnector
        {
            public partial class SceneHandler
            {
                public class Main : SimonMsg
                {
                    public static string InterfaceName = "sceneConnector.sceneHandler.main";



                }
            }
        }
        public partial class SceneConnector
        {
            public partial class CardHandler
            {
                public class SetBattleCardGroup : SimonMsg
                {
                    public static string InterfaceName = "sceneConnector.cardHandler.setBattleCardGroup";

                    public List<int> cidList;

                    public SetBattleCardGroup(List<int> cidList)
                    {
                        this.cidList = cidList;
                    }


                }
            }
        }
        public partial class SceneConnector
        {
            public partial class CardHandler
            {
                public class GetBattleCardGroup : SimonMsg
                {
                    public static string InterfaceName = "sceneConnector.cardHandler.getBattleCardGroup";



                }
            }
        }
        public partial class SceneConnector
        {
            public partial class CardHandler
            {
                public class CardList : SimonMsg
                {
                    public static string InterfaceName = "sceneConnector.cardHandler.cardList";



                }
            }
        }
        public partial class SceneConnector
        {
            public partial class CardHandler
            {
                public class HandleRedundantCard : SimonMsg
                {
                    public static string InterfaceName = "sceneConnector.cardHandler.handleRedundantCard";



                }
            }
        }
        public partial class SceneConnector
        {
            public partial class CardHandler
            {
                public class Upgrade : SimonMsg
                {
                    public static string InterfaceName = "sceneConnector.cardHandler.upgrade";

                    public int cid;

                    public Upgrade(int cid)
                    {
                        this.cid = cid;
                    }


                }
            }
        }
        public partial class SceneConnector
        {
            public partial class RankHandler
            {
                public class RankingList : SimonMsg
                {
                    public static string InterfaceName = "sceneConnector.rankHandler.rankingList";

                    public int top;

                    public RankingList(int top)
                    {
                        this.top = top;
                    }


                }
            }
        }
        public partial class SceneConnector
        {
            public partial class HistoryHandler
            {
                public class Get1V1Record : SimonMsg
                {
                    public static string InterfaceName = "sceneConnector.historyHandler.get1V1Record";

                    public int recordId;

                    public Get1V1Record(int recordId)
                    {
                        this.recordId = recordId;
                    }


                }
            }
        }
        public partial class SceneConnector
        {
            public partial class HistoryHandler
            {
                public class GetHistory1V1List : SimonMsg
                {
                    public static string InterfaceName = "sceneConnector.historyHandler.getHistory1V1List";

                    public int top;

                    public GetHistory1V1List(int top)
                    {
                        this.top = top;
                    }


                }
            }
        }
        public partial class SceneConnector
        {
            public partial class BoxHandler
            {
                public class BoxList : SimonMsg
                {
                    public static string InterfaceName = "sceneConnector.boxHandler.boxList";



                }
            }
        }
        public partial class SceneConnector
        {
            public partial class BoxHandler
            {
                public class StartUnlockBox : SimonMsg
                {
                    public static string InterfaceName = "sceneConnector.boxHandler.startUnlockBox";

                    public int seat;

                    public StartUnlockBox(int seat)
                    {
                        this.seat = seat;
                    }


                }
            }
        }
        public partial class SceneConnector
        {
            public partial class BoxHandler
            {
                public class OpenBox : SimonMsg
                {
                    public static string InterfaceName = "sceneConnector.boxHandler.openBox";

                    public int seat;

                    public OpenBox(int seat)
                    {
                        this.seat = seat;
                    }


                }
            }
        }
        public partial class SceneConnector
        {
            public partial class AchieveHandler
            {
                public class GetAchievementList : SimonMsg
                {
                    public static string InterfaceName = "sceneConnector.achieveHandler.getAchievementList";



                }
            }
        }
        public partial class SceneConnector
        {
            public partial class AchieveHandler
            {
                public class FinishAchievement : SimonMsg
                {
                    public static string InterfaceName = "sceneConnector.achieveHandler.finishAchievement";

                    public int achieveType;

                    public int achieveId;

                    public FinishAchievement(int achieveType,int achieveId)
                    {
                        this.achieveType = achieveType;
                        this.achieveId = achieveId;
                    }


                }
            }
        }
        public partial class SceneConnector
        {
            public partial class TaskHandler
            {
                public class GetTaskList : SimonMsg
                {
                    public static string InterfaceName = "sceneConnector.taskHandler.getTaskList";



                }
            }
        }
        public partial class SceneConnector
        {
            public partial class TaskHandler
            {
                public class FinishTask : SimonMsg
                {
                    public static string InterfaceName = "sceneConnector.taskHandler.finishTask";

                    public int taskType;

                    public FinishTask(int taskType)
                    {
                        this.taskType = taskType;
                    }


                }
            }
        }
        public partial class SceneConnector
        {
            public partial class TowerHandler
            {
                public class GetRestTowerCount : SimonMsg
                {
                    public static string InterfaceName = "sceneConnector.towerHandler.getRestTowerCount";



                }
            }
        }
        public partial class SceneConnector
        {
            public partial class TowerHandler
            {
                public class FinishTowerWave : SimonMsg
                {
                    public static string InterfaceName = "sceneConnector.towerHandler.finishTowerWave";

                    public int wave;

                    public FinishTowerWave(int wave)
                    {
                        this.wave = wave;
                    }


                }
            }
        }
        public partial class Scene
        {
            public partial class TowerHandler
            {
                public class StartTower : SimonMsg
                {
                    public static string InterfaceName = "scene.towerHandler.startTower";

                    public int difficulty;

                    public StartTower(int difficulty)
                    {
                        this.difficulty = difficulty;
                    }


                }
            }
        }
        public partial class Scene
        {
            public partial class TowerHandler
            {
                public class EndTower : SimonMsg
                {
                    public static string InterfaceName = "scene.towerHandler.endTower";



                }
            }
        }
        public partial class SceneConnector
        {
            public partial class MailHandler
            {
                public class GetMailList : SimonMsg
                {
                    public static string InterfaceName = "sceneConnector.mailHandler.getMailList";



                }
            }
        }
        public partial class SceneConnector
        {
            public partial class MailHandler
            {
                public class ReadMail : SimonMsg
                {
                    public static string InterfaceName = "sceneConnector.mailHandler.readMail";

                    public int type;

                    public string registerTime;

                    public ReadMail(int type,string registerTime)
                    {
                        this.type = type;
                        this.registerTime = registerTime;
                    }


                }
            }
        }
        public partial class SceneConnector
        {
            public partial class MailHandler
            {
                public class GetMailAward : SimonMsg
                {
                    public static string InterfaceName = "sceneConnector.mailHandler.getMailAward";

                    public int type;

                    public string registerTime;

                    public GetMailAward(int type,string registerTime)
                    {
                        this.type = type;
                        this.registerTime = registerTime;
                    }


                }
            }
        }
        public partial class SceneConnector
        {
            public partial class VirusHandler
            {
                public class GetVirusCode : SimonMsg
                {
                    public static string InterfaceName = "sceneConnector.virusHandler.getVirusCode";



                }
            }
        }
        public partial class SceneConnector
        {
            public partial class VirusHandler
            {
                public class GetRecruitAward : SimonMsg
                {
                    public static string InterfaceName = "sceneConnector.virusHandler.getRecruitAward";



                }
            }
        }
        public partial class Scene
        {
            public partial class VirusHandler
            {
                public class InfectVirus : SimonMsg
                {
                    public static string InterfaceName = "scene.virusHandler.infectVirus";

                    public string virusCode;

                    public InfectVirus(string virusCode)
                    {
                        this.virusCode = virusCode;
                    }


                }
            }
        }
        public partial class SceneConnector
        {
            public partial class VirusHandler
            {
                public class GetVirusList : SimonMsg
                {
                    public static string InterfaceName = "sceneConnector.virusHandler.getVirusList";



                }
            }
        }
        public partial class SceneConnector
        {
            public partial class VirusHandler
            {
                public class ClearVirus : SimonMsg
                {
                    public static string InterfaceName = "sceneConnector.virusHandler.clearVirus";

                    public int virusType;

                    public int virusId;

                    public ClearVirus(int virusType,int virusId)
                    {
                        this.virusType = virusType;
                        this.virusId = virusId;
                    }


                }
            }
        }
        public partial class SceneConnector
        {
            public partial class QuickLoginHandler
            {
                public class VerifyGameCenterToken : SimonMsg
                {
                    public static string InterfaceName = "sceneConnector.quickLoginHandler.verifyGameCenterToken";

                    public string authString;

                    public VerifyGameCenterToken(string authString)
                    {
                        this.authString = authString;
                    }


                }
            }
        }
        public partial class SceneConnector
        {
            public partial class QuickLoginHandler
            {
                public class AppleLoginWithUniqueID : SimonMsg
                {
                    public static string InterfaceName = "sceneConnector.quickLoginHandler.appleLoginWithUniqueID";

                    public int type;

                    public string uniqueID;

                    public string cFrom;

                    public string region;

                    public AppleLoginWithUniqueID(int type,string uniqueID,string cFrom,string region)
                    {
                        this.type = type;
                        this.uniqueID = uniqueID;
                        this.cFrom = cFrom;
                        this.region = region;
                    }


                }
            }
        }
        public partial class SceneConnector
        {
            public partial class QuickLoginHandler
            {
                public class VerifyDeviceVersion : SimonMsg
                {
                    public static string InterfaceName = "sceneConnector.quickLoginHandler.verifyDeviceVersion";

                    public string appVersion;

                    public string resVersion;

                    public string platform;

                    public VerifyDeviceVersion(string appVersion,string resVersion,string platform)
                    {
                        this.appVersion = appVersion;
                        this.resVersion = resVersion;
                        this.platform = platform;
                    }


                }
            }
        }
        public partial class SceneConnector
        {
            public partial class FeedbackHandler
            {
                public class GetRestFeedbackCountToday : SimonMsg
                {
                    public static string InterfaceName = "sceneConnector.feedbackHandler.getRestFeedbackCountToday";



                }
            }
        }
        public partial class SceneConnector
        {
            public partial class FeedbackHandler
            {
                public class Feedback : SimonMsg
                {
                    public static string InterfaceName = "sceneConnector.feedbackHandler.feedback";

                    public string content;

                    public Feedback(string content)
                    {
                        this.content = content;
                    }


                }
            }
        }
        public partial class Version
        {
            public partial class VersionHandler
            {
                public class GetGateServer : SimonMsg
                {
                    public static string InterfaceName = "version.versionHandler.getGateServer";

                    public string appVersion;

                    public GetGateServer(string appVersion)
                    {
                        this.appVersion = appVersion;
                    }


                }
            }
        }
    }

    public class ServerResponseInterFace
    {
        public partial class Gate
        {
            public partial class GateHandler
            {
                public class GetGameConnector
                {
                    public static string InterfaceName = "gate.gateHandler.getGameConnector";

                    public int code;

                    public string errorMsg;

                    public string host;

                    public int port;


                }
            }
        }
        public partial class Gate
        {
            public partial class GateHandler
            {
                public class GetSceneConnector
                {
                    public static string InterfaceName = "gate.gateHandler.getSceneConnector";

                    public int code;

                    public string errorMsg;

                    public string host;

                    public int port;


                }
            }
        }
        public partial class GameConnector
        {
            public partial class EntryHandler
            {
                public class EnterMatchQueue
                {
                    public static string InterfaceName = "gameConnector.entryHandler.enterMatchQueue";

                    public int code;

                    public string errorMsg;

                    public int emtime;


                }
            }
        }
        public partial class GameConnector
        {
            public partial class EntryHandler
            {
                public class ReconnectFightArea
                {
                    public static string InterfaceName = "gameConnector.entryHandler.reconnectFightArea";

                    public int code;

                    public string errorMsg;


                }
            }
        }
        public partial class GameConnector
        {
            public partial class EntryHandler
            {
                public class EnterFightAreaAfterInvited
                {
                    public static string InterfaceName = "gameConnector.entryHandler.enterFightAreaAfterInvited";

                    public int code;

                    public string errorMsg;


                }
            }
        }
        public partial class Fight
        {
            public partial class FightHandler
            {
                public class GetActionsHistory
                {
                    public static string InterfaceName = "fight.fightHandler.getActionsHistory";

                    public class Command
                    {
                    public int executeFrame;

                    public int numberID;

                    public int type;

                    public List<int> paramsList;

                    }

                    public int code;

                    public string errorMsg;

                    public List<Command> commands;


                }
            }
        }
        public partial class Fight
        {
            public partial class FightHandler
            {
                public class RecallOnAllPlayersReadyMessage
                {
                    public static string InterfaceName = "fight.fightHandler.recallOnAllPlayersReadyMessage";

                    public class PlayerInfo
                    {
                    public int numberID;

                    public string nickname;

                    public int integral;

                    public int portrait;

                    public int seat;

                    public string cardIds;

                    public string battleCardGroup;

                    }

                    public int code;

                    public string errorMsg;

                    public List<PlayerInfo> playerInfoList;

                    public int randomSeed;

                    public int keyFrameRange;

                    public int clientStartDelay;

                    public int battleID;


                }
            }
        }
        public partial class Fight
        {
            public partial class FightHandler
            {
                public class Fight
                {
                    public static string InterfaceName = "fight.fightHandler.fight";

                    public int code;

                    public string errorMsg;


                }
            }
        }
        public partial class Fight
        {
            public partial class FightHandler
            {
                public class Ready
                {
                    public static string InterfaceName = "fight.fightHandler.ready";

                    public int code;

                    public string errorMsg;


                }
            }
        }
        public partial class Fight
        {
            public partial class FightHandler
            {
                public class StartFight
                {
                    public static string InterfaceName = "fight.fightHandler.startFight";

                    public int code;

                    public string errorMsg;


                }
            }
        }
        public partial class Fight
        {
            public partial class FightHandler
            {
                public class EndFight
                {
                    public static string InterfaceName = "fight.fightHandler.endFight";

                    public int code;

                    public string errorMsg;


                }
            }
        }
        public partial class Match
        {
            public partial class MatchHandler
            {
                public class CancelMatch
                {
                    public static string InterfaceName = "match.matchHandler.cancelMatch";

                    public int code;

                    public string errorMsg;


                }
            }
        }
        public partial class Scene
        {
            public partial class FriendHandler
            {
                public class ReplyFriendGameInvitation
                {
                    public static string InterfaceName = "scene.friendHandler.replyFriendGameInvitation";

                    public int code;

                    public string errorMsg;


                }
            }
        }
        public partial class Scene
        {
            public partial class FriendHandler
            {
                public class CancelFriendGameInvitation
                {
                    public static string InterfaceName = "scene.friendHandler.cancelFriendGameInvitation";

                    public int code;

                    public string errorMsg;


                }
            }
        }
        public partial class Scene
        {
            public partial class FriendHandler
            {
                public class Chat
                {
                    public static string InterfaceName = "scene.friendHandler.chat";

                    public int code;

                    public string errorMsg;


                }
            }
        }
        public partial class Scene
        {
            public partial class FriendHandler
            {
                public class SendFriendGameInvitation
                {
                    public static string InterfaceName = "scene.friendHandler.sendFriendGameInvitation";

                    public int code;

                    public string errorMsg;


                }
            }
        }
        public partial class Scene
        {
            public partial class FriendHandler
            {
                public class SendAddFriendMsg
                {
                    public static string InterfaceName = "scene.friendHandler.sendAddFriendMsg";

                    public int code;

                    public string errorMsg;


                }
            }
        }
        public partial class Scene
        {
            public partial class FriendHandler
            {
                public class InitFriendsList
                {
                    public static string InterfaceName = "scene.friendHandler.initFriendsList";

                    public class FriendInfo
                    {
                    public int numberID;

                    public string nickname;

                    public int portrait;

                    public int mainState;

                    }

                    public class AddFriendInvitation
                    {
                    public int numberID;

                    public string nickname;

                    public int portrait;

                    }

                    public int code;

                    public string errorMsg;

                    public List<FriendInfo> friendInfoList;

                    public List<AddFriendInvitation> addFriendInvitationList;

                    public int virusRequiredGrade;


                }
            }
        }
        public partial class Scene
        {
            public partial class FriendHandler
            {
                public class ReplyAddFriendInvitation
                {
                    public static string InterfaceName = "scene.friendHandler.replyAddFriendInvitation";

                    public int code;

                    public int isOnline;

                    public string errorMsg;


                }
            }
        }
        public partial class SceneConnector
        {
            public partial class BoxHandler
            {
                public class StartUnlockBox
                {
                    public static string InterfaceName = "sceneConnector.boxHandler.startUnlockBox";

                    public int code;

                    public string errorMsg;


                }
            }
        }
        public partial class SceneConnector
        {
            public partial class UserHandler
            {
                public class Login
                {
                    public static string InterfaceName = "sceneConnector.userHandler.login";

                    public int code;

                    public string errorMsg;

                    public string userBasicInfoStr;


                }
            }
        }
        public partial class SceneConnector
        {
            public partial class UserHandler
            {
                public class Register
                {
                    public static string InterfaceName = "sceneConnector.userHandler.register";

                    public int code;

                    public string errorMsg;

                    public string userBasicInfoStr;


                }
            }
        }
        public partial class SceneConnector
        {
            public partial class UserHandler
            {
                public class UserDetail
                {
                    public static string InterfaceName = "sceneConnector.userHandler.userDetail";

                    public int code;

                    public string errorMsg;

                    public int numberID;

                    public string nickname;

                    public int integral;

                    public int grade;

                    public int highestIntegral;

                    public int victoryBattle1v1;

                    public int totalBattle1v1;

                    public int portrait;

                    public int cardCount;

                    public int isFriend;

                    public List<int> userBattleCardGroup;


                }
            }
        }
        public partial class SceneConnector
        {
            public partial class UserHandler
            {
                public class UpdateNickname
                {
                    public static string InterfaceName = "sceneConnector.userHandler.updateNickname";

                    public int code;

                    public string errorMsg;

                    public string nickname;


                }
            }
        }
        public partial class SceneConnector
        {
            public partial class UserHandler
            {
                public class UpdatePortrait
                {
                    public static string InterfaceName = "sceneConnector.userHandler.updatePortrait";

                    public int code;

                    public string errorMsg;


                }
            }
        }
        public partial class SceneConnector
        {
            public partial class UserHandler
            {
                public class UpdatePassword
                {
                    public static string InterfaceName = "sceneConnector.userHandler.updatePassword";

                    public int code;

                    public string errorMsg;


                }
            }
        }
        public partial class SceneConnector
        {
            public partial class GuideHandler
            {
                public class FinishGuideStep
                {
                    public static string InterfaceName = "sceneConnector.guideHandler.finishGuideStep";

                    public int code;

                    public string errorMsg;

                    public int nextStep;


                }
            }
        }
        public partial class SceneConnector
        {
            public partial class TrainingHandler
            {
                public class FinishTrainingStep
                {
                    public static string InterfaceName = "sceneConnector.trainingHandler.finishTrainingStep";

                    public int code;

                    public string errorMsg;

                    public class card
                    {
                    public int cid;

                    public int count;

                    }

                    public card cardList;

                    public int jewel;

                    public int gold;

                    public class box
                    {
                    public int bid;

                    public int grade;

                    public int seat;

                    }

                    public box boxInfo;

                    public int nextTrainingStep;


                }
            }
        }
        public partial class SceneConnector
        {
            public partial class FriendHandler
            {
                public class Search
                {
                    public static string InterfaceName = "sceneConnector.friendHandler.search";

                    public int code;

                    public string errorMsg;

                    public int numberID;

                    public string nickname;

                    public int portrait;

                    public int isFriend;


                }
            }
        }
        public partial class SceneConnector
        {
            public partial class FriendHandler
            {
                public class Delete
                {
                    public static string InterfaceName = "sceneConnector.friendHandler.delete";

                    public int code;

                    public string errorMsg;


                }
            }
        }
        public partial class SceneConnector
        {
            public partial class ShopHandler
            {
                public class GetShopList
                {
                    public static string InterfaceName = "sceneConnector.shopHandler.getShopList";

                    public class SellBoxInfo
                    {
                    public int boxId;

                    public int boxGrade;

                    public int costJewel;

                    public int boxSeat;

                    }

                    public class SellGoldInfo
                    {
                    public string iconName;

                    public string description;

                    public int goldOutput;

                    public int costJewel;

                    }

                    public class SellCardInfo
                    {
                    public int cardId;

                    public int costGold;

                    public int cardRarity;

                    public int batchTenCostGold;

                    }

                    public class SellJewelInfo
                    {
                    public string iconName;

                    public string description;

                    public int jewelOutput;

                    public int costRMB;

                    public string itunesId;

                    public int isFirstRecharge;

                    }

                    public int code;

                    public string errorMsg;

                    public int restRefreshCount;

                    public int nextRefreshCost;

                    public string nextShopRefreshTime;

                    public List<SellGoldInfo> sellGoldList;

                    public List<SellCardInfo> sellCardList;

                    public List<SellBoxInfo> sellBoxList;

                    public List<SellJewelInfo> sellJewelList;


                }
            }
        }
        public partial class SceneConnector
        {
            public partial class ShopHandler
            {
                public class RefreshSellCardList
                {
                    public static string InterfaceName = "sceneConnector.shopHandler.refreshSellCardList";

                    public class SellCardList
                    {
                    public int cardId;

                    public int costGold;

                    public int cardRarity;

                    public int batchTenCostGold;

                    }

                    public int code;

                    public int restRefreshCount;

                    public int nextRefreshCost;

                    public List<SellCardList> sellCardList;

                    public string errorMsg;


                }
            }
        }
        public partial class SceneConnector
        {
            public partial class ShopHandler
            {
                public class BuyShopCard
                {
                    public static string InterfaceName = "sceneConnector.shopHandler.buyShopCard";

                    public int code;

                    public int nextCostGold;

                    public int nextTenCostGold;

                    public string errorMsg;


                }
            }
        }
        public partial class SceneConnector
        {
            public partial class ShopHandler
            {
                public class BuyShopBox
                {
                    public static string InterfaceName = "sceneConnector.shopHandler.buyShopBox";

                    public class Card
                    {
                    public int cid;

                    public int count;

                    }

                    public int code;

                    public List<Card> cardList;

                    public string errorMsg;


                }
            }
        }
        public partial class SceneConnector
        {
            public partial class ShopHandler
            {
                public class BuyShopGold
                {
                    public static string InterfaceName = "sceneConnector.shopHandler.buyShopGold";

                    public int code;

                    public string errorMsg;


                }
            }
        }
        public partial class SceneConnector
        {
            public partial class ShopHandler
            {
                public class BuyShopJewel
                {
                    public static string InterfaceName = "sceneConnector.shopHandler.buyShopJewel";

                    public int code;

                    public string errorMsg;

                    public string clientNeededIndex;

                    public int jewelOutPut;

                    public string itunesId;


                }
            }
        }
        public partial class SceneConnector
        {
            public partial class TavernHandler
            {
                public class GetList
                {
                    public static string InterfaceName = "sceneConnector.tavernHandler.getList";

                    public int code;

                    public class TavernInfo
                    {
                    public int tavernFlag;

                    public int restTime;

                    public int restCount;

                    public int totalCount;

                    }

                    public TavernInfo normalTavern;

                    public TavernInfo seniorTavern;

                    public string errorMsg;


                }
            }
        }
        public partial class SceneConnector
        {
            public partial class TavernHandler
            {
                public class Recruit
                {
                    public static string InterfaceName = "sceneConnector.tavernHandler.recruit";

                    public class Card
                    {
                    public int cid;

                    public int count;

                    }

                    public int code;

                    public int restTime;

                    public int restCount;

                    public int bid;

                    public List<Card> cardList;

                    public string errorMsg;


                }
            }
        }
        public partial class SceneConnector
        {
            public partial class SignInHandler
            {
                public class GetList
                {
                    public static string InterfaceName = "sceneConnector.signInHandler.getList";

                    public class Card
                    {
                    public int cid;

                    public int count;

                    }

                    public class Award
                    {
                    public int awardType;

                    public int awardDetail;

                    public int awardDescriptionId;

                    public List<Card> cardList;

                    }

                    public class SignInData
                    {
                    public int day;

                    public int signInFlag;

                    public List<Award> awardList;

                    }

                    public int code;

                    public int signInMonth;

                    public int signInCount;

                    public int todayCanSignInFlag;

                    public List<SignInData> signInData;

                    public string signInHeroIcon;

                    public string signInHeroName;

                    public string signInHeroDescription;

                    public string errorMsg;


                }
            }
        }
        public partial class SceneConnector
        {
            public partial class SignInHandler
            {
                public class SignInToday
                {
                    public static string InterfaceName = "sceneConnector.signInHandler.signInToday";

                    public class Card
                    {
                    public int cid;

                    public int count;

                    }

                    public class Award
                    {
                    public int awardType;

                    public int awardDetail;

                    public int awardDescriptionId;

                    public List<Card> cardList;

                    }

                    public int code;

                    public List<Award> signInAward;

                    public string errorMsg;


                }
            }
        }
        public partial class SceneConnector
        {
            public partial class SceneHandler
            {
                public class Main
                {
                    public static string InterfaceName = "sceneConnector.sceneHandler.main";

                    public int code;

                    public class UserGameInfo
                    {
                    public int numberID;

                    public string nickname;

                    public int integral;

                    public int grade;

                    public int portrait;

                    public int gold;

                    public int jewel;

                    public bool isGaming;

                    public string nextGuideStep;

                    }

                    public UserGameInfo userGameInfo;

                    public string errorMsg;


                }
            }
        }
        public partial class SceneConnector
        {
            public partial class CardHandler
            {
                public class CardList
                {
                    public static string InterfaceName = "sceneConnector.cardHandler.cardList";

                    public int code;

                    public class Card
                    {
                    public int cardId;

                    public int count;

                    public int level;

                    }

                    public List<Card> cardList;

                    public string errorMsg;


                }
            }
        }
        public partial class SceneConnector
        {
            public partial class CardHandler
            {
                public class HandleRedundantCard
                {
                    public static string InterfaceName = "sceneConnector.cardHandler.handleRedundantCard";

                    public class Card
                    {
                    public int cid;

                    public int count;

                    public int cost;

                    }

                    public int code;

                    public int gold;

                    public List<Card> cardList;

                    public string errorMsg;


                }
            }
        }
        public partial class SceneConnector
        {
            public partial class CardHandler
            {
                public class SetBattleCardGroup
                {
                    public static string InterfaceName = "sceneConnector.cardHandler.setBattleCardGroup";

                    public int code;

                    public string errorMsg;


                }
            }
        }
        public partial class SceneConnector
        {
            public partial class CardHandler
            {
                public class GetBattleCardGroup
                {
                    public static string InterfaceName = "sceneConnector.cardHandler.getBattleCardGroup";

                    public int code;

                    public string errorMsg;

                    public List<int> cardsList;


                }
            }
        }
        public partial class SceneConnector
        {
            public partial class CardHandler
            {
                public class Upgrade
                {
                    public static string InterfaceName = "sceneConnector.cardHandler.upgrade";

                    public int code;

                    public string errorMsg;

                    public int cid;

                    public int count;

                    public int level;


                }
            }
        }
        public partial class SceneConnector
        {
            public partial class BoxHandler
            {
                public class BoxList
                {
                    public static string InterfaceName = "sceneConnector.boxHandler.boxList";

                    public class Box
                    {
                    public int id;

                    public int restTime;

                    public int startUnlockFlag;

                    public int seat;

                    public int grade;

                    }

                    public int code;

                    public List<Box> boxList;

                    public string errorMsg;


                }
            }
        }
        public partial class SceneConnector
        {
            public partial class RankHandler
            {
                public class RankingList
                {
                    public static string InterfaceName = "sceneConnector.rankHandler.rankingList";

                    public int code;

                    public class Ranking
                    {
                    public int ranking;

                    public int changeRanking;

                    public int numberID;

                    public string nickname;

                    public int integral;

                    public int grade;

                    public int portrait;

                    }

                    public List<Ranking> rankingList;

                    public int myRanking;

                    public string currentRankTime;

                    public string nextRankTime;

                    public string errorMsg;


                }
            }
        }
        public partial class SceneConnector
        {
            public partial class HistoryHandler
            {
                public class Get1V1Record
                {
                    public static string InterfaceName = "sceneConnector.historyHandler.get1V1Record";

                    public class Command
                    {
                    public int executeFrame;

                    public int numberID;

                    public int type;

                    public List<int> paramsList;

                    }

                    public int code;

                    public int randomSeed;

                    public string battleCardGroup;

                    public string cardList;

                    public string opponentBattleCardGroup;

                    public string opponentCardList;

                    public int keyFrameRange;

                    public int clientStartDelay;

                    public List<Command> commands;

                    public string errorMsg;


                }
            }
        }
        public partial class SceneConnector
        {
            public partial class HistoryHandler
            {
                public class GetHistory1V1List
                {
                    public static string InterfaceName = "sceneConnector.historyHandler.getHistory1V1List";

                    public class History1V1
                    {
                    public int recordId;

                    public int integral;

                    public int seat;

                    public int result;

                    public int battleId;

                    public int changeIntegral;

                    public int opponentNumberID;

                    public int opponentIntegral;

                    public string opponentNickname;

                    public int opponentPortrait;

                    public string pastTime;

                    public int canReplay;

                    public int gameMode;

                    }

                    public int code;

                    public List<History1V1> history1V1List;

                    public string errorMsg;


                }
            }
        }
        public partial class SceneConnector
        {
            public partial class BoxHandler
            {
                public class OpenBox
                {
                    public static string InterfaceName = "sceneConnector.boxHandler.openBox";

                    public int code;

                    public class Card
                    {
                    public int cid;

                    public int count;

                    }

                    public List<Card> cardList;

                    public string errorMsg;


                }
            }
        }
        public partial class SceneConnector
        {
            public partial class AchieveHandler
            {
                public class GetAchievementList
                {
                    public static string InterfaceName = "sceneConnector.achieveHandler.getAchievementList";

                    public class Card
                    {
                    public int cid;

                    public int count;

                    }

                    public class Award
                    {
                    public int awardType;

                    public int awardDetail;

                    public int awardDescriptionId;

                    public List<Card> cardList;

                    }

                    public class Achieve
                    {
                    public int type;

                    public int achieveId;

                    public string iconName;

                    public string name;

                    public string description;

                    public string enterBtn;

                    public int detail;

                    public int currentDetail;

                    public int processFlag;

                    public List<Award> awardList;

                    }

                    public int code;

                    public List<Achieve> achievementList;

                    public string errorMsg;


                }
            }
        }
        public partial class SceneConnector
        {
            public partial class AchieveHandler
            {
                public class FinishAchievement
                {
                    public static string InterfaceName = "sceneConnector.achieveHandler.finishAchievement";

                    public class Card
                    {
                    public int cid;

                    public int count;

                    }

                    public class Award
                    {
                    public int awardType;

                    public int awardDetail;

                    public List<Card> cardList;

                    public int awardDescriptionId;

                    }

                    public int code;

                    public List<Award> awardList;

                    public int type;

                    public int achieveId;

                    public string iconName;

                    public string name;

                    public string description;

                    public string enterBtn;

                    public int detail;

                    public int currentDetail;

                    public int processFlag;

                    public List<Award> nextAwardList;

                    public string errorMsg;


                }
            }
        }
        public partial class SceneConnector
        {
            public partial class TaskHandler
            {
                public class GetTaskList
                {
                    public static string InterfaceName = "sceneConnector.taskHandler.getTaskList";

                    public class Card
                    {
                    public int cid;

                    public int count;

                    }

                    public class Award
                    {
                    public int awardType;

                    public int awardDetail;

                    public List<Card> cardList;

                    public int awardDescriptionId;

                    }

                    public class Task
                    {
                    public int type;

                    public string iconName;

                    public string name;

                    public string description;

                    public int detail;

                    public string enterBtn;

                    public int currentDetail;

                    public List<Award> awardList;

                    public int processFlag;

                    }

                    public int code;

                    public List<Task> taskList;

                    public string errorMsg;


                }
            }
        }
        public partial class SceneConnector
        {
            public partial class TaskHandler
            {
                public class FinishTask
                {
                    public static string InterfaceName = "sceneConnector.taskHandler.finishTask";

                    public class Card
                    {
                    public int cid;

                    public int count;

                    }

                    public class Award
                    {
                    public int awardType;

                    public int awardDetail;

                    public List<Card> cardList;

                    public int awardDescriptionId;

                    }

                    public int code;

                    public List<Award> awardList;

                    public string errorMsg;


                }
            }
        }
        public partial class SceneConnector
        {
            public partial class TowerHandler
            {
                public class GetRestTowerCount
                {
                    public static string InterfaceName = "sceneConnector.towerHandler.getRestTowerCount";

                    public int code;

                    public int restCount;

                    public int totalCount;

                    public string errorMsg;


                }
            }
        }
        public partial class SceneConnector
        {
            public partial class TowerHandler
            {
                public class FinishTowerWave
                {
                    public static string InterfaceName = "sceneConnector.towerHandler.finishTowerWave";

                    public int code;

                    public int gold;

                    public int jewel;

                    public string errorMsg;


                }
            }
        }
        public partial class Scene
        {
            public partial class TowerHandler
            {
                public class StartTower
                {
                    public static string InterfaceName = "scene.towerHandler.startTower";

                    public int code;

                    public string errorMsg;


                }
            }
        }
        public partial class Scene
        {
            public partial class TowerHandler
            {
                public class EndTower
                {
                    public static string InterfaceName = "scene.towerHandler.endTower";

                    public int code;

                    public string errorMsg;


                }
            }
        }
        public partial class SceneConnector
        {
            public partial class MailHandler
            {
                public class GetMailList
                {
                    public static string InterfaceName = "sceneConnector.mailHandler.getMailList";

                    public class Card
                    {
                    public int cid;

                    public int count;

                    public string description;

                    }

                    public class Award
                    {
                    public int awardType;

                    public int awardDetail;

                    public int awardDescriptionId;

                    public List<Card> cardList;

                    }

                    public class Mail
                    {
                    public int type;

                    public string registerTime;

                    public string title;

                    public string content;

                    public string sendTime;

                    public List<Award> awardList;

                    public int isRead;

                    public int isGetAward;

                    }

                    public int code;

                    public List<Mail> mails;

                    public string errorMsg;


                }
            }
        }
        public partial class SceneConnector
        {
            public partial class MailHandler
            {
                public class ReadMail
                {
                    public static string InterfaceName = "sceneConnector.mailHandler.readMail";

                    public int code;

                    public string errorMsg;


                }
            }
        }
        public partial class SceneConnector
        {
            public partial class MailHandler
            {
                public class GetMailAward
                {
                    public static string InterfaceName = "sceneConnector.mailHandler.getMailAward";

                    public class Card
                    {
                    public int cid;

                    public int count;

                    public string description;

                    }

                    public class Award
                    {
                    public int awardType;

                    public int awardDetail;

                    public int awardDescriptionId;

                    public List<Card> cardList;

                    }

                    public int code;

                    public string errorMsg;

                    public List<Award> awardList;


                }
            }
        }
        public partial class SceneConnector
        {
            public partial class VirusHandler
            {
                public class GetVirusCode
                {
                    public static string InterfaceName = "sceneConnector.virusHandler.getVirusCode";

                    public int code;

                    public string errorMsg;

                    public string virusCode;


                }
            }
        }
        public partial class SceneConnector
        {
            public partial class VirusHandler
            {
                public class GetRecruitAward
                {
                    public static string InterfaceName = "sceneConnector.virusHandler.getRecruitAward";

                    public class Card
                    {
                    public int cid;

                    public int count;

                    }

                    public class Award
                    {
                    public int awardType;

                    public int awardDetail;

                    public List<Card> cardList;

                    public int awardDescriptionId;

                    }

                    public int code;

                    public string errorMsg;

                    public int isAlreadyGet;

                    public List<Award> awardList;


                }
            }
        }
        public partial class Scene
        {
            public partial class VirusHandler
            {
                public class InfectVirus
                {
                    public static string InterfaceName = "scene.virusHandler.infectVirus";

                    public int code;

                    public string errorMsg;


                }
            }
        }
        public partial class SceneConnector
        {
            public partial class VirusHandler
            {
                public class GetVirusList
                {
                    public static string InterfaceName = "sceneConnector.virusHandler.getVirusList";

                    public class Card
                    {
                    public int cid;

                    public int count;

                    }

                    public class Award
                    {
                    public int awardType;

                    public int awardDetail;

                    public List<Card> cardList;

                    public int awardDescriptionId;

                    }

                    public class Virus
                    {
                    public int virusType;

                    public int virusId;

                    public string name;

                    public string description;

                    public int detail;

                    public int isFinish;

                    public List<Award> awardList;

                    }

                    public int code;

                    public string errorMsg;

                    public int virusCount;

                    public List<Virus> virusList;


                }
            }
        }
        public partial class SceneConnector
        {
            public partial class VirusHandler
            {
                public class ClearVirus
                {
                    public static string InterfaceName = "sceneConnector.virusHandler.clearVirus";

                    public class Card
                    {
                    public int cid;

                    public int count;

                    }

                    public class Award
                    {
                    public int awardType;

                    public int awardDetail;

                    public List<Card> cardList;

                    public int awardDescriptionId;

                    }

                    public int code;

                    public string errorMsg;

                    public int nextVirusType;

                    public int nextVirusId;

                    public string name;

                    public string description;

                    public int detail;

                    public int isFinish;

                    public List<Award> awardList;


                }
            }
        }
        public partial class SceneConnector
        {
            public partial class QuickLoginHandler
            {
                public class VerifyDeviceVersion
                {
                    public static string InterfaceName = "sceneConnector.quickLoginHandler.verifyDeviceVersion";

                    public int code;

                    public string errorMsg;

                    public string downLoadUrl;


                }
            }
        }
        public partial class SceneConnector
        {
            public partial class QuickLoginHandler
            {
                public class VerifyGameCenterToken
                {
                    public static string InterfaceName = "sceneConnector.quickLoginHandler.verifyGameCenterToken";

                    public int code;

                    public string errorMsg;

                    public int needReLogin;

                    public string gameCenterID;

                    public string nickname;

                    public int grade;


                }
            }
        }
        public partial class SceneConnector
        {
            public partial class QuickLoginHandler
            {
                public class AppleLoginWithUniqueID
                {
                    public static string InterfaceName = "sceneConnector.quickLoginHandler.appleLoginWithUniqueID";

                    public int code;

                    public string errorMsg;

                    public string userBasicInfoStr;


                }
            }
        }
        public partial class SceneConnector
        {
            public partial class FeedbackHandler
            {
                public class GetRestFeedbackCountToday
                {
                    public static string InterfaceName = "sceneConnector.feedbackHandler.getRestFeedbackCountToday";

                    public int code;

                    public string errorMsg;

                    public int restCount;


                }
            }
        }
        public partial class SceneConnector
        {
            public partial class FeedbackHandler
            {
                public class Feedback
                {
                    public static string InterfaceName = "sceneConnector.feedbackHandler.feedback";

                    public int code;

                    public string errorMsg;


                }
            }
        }
        public partial class Version
        {
            public partial class VersionHandler
            {
                public class GetGateServer
                {
                    public static string InterfaceName = "version.versionHandler.getGateServer";

                    public int code;

                    public string errorMsg;

                    public string host;

                    public int port;


                }
            }
        }
    }

    public class ServerPushInterface
    {
        public class OnKeyFrame
        {
                    public static string InterfaceName = "onKeyFrame";

                    public class Command
                    {
                    public int executeFrame;

                    public int numberID;

                    public int type;

                    public List<int> paramsList;

                    }

                    public int nextKeyFrame;

                    public List<Command> commands;


        }
        public class OnAllPlayersReady
        {
                    public static string InterfaceName = "onAllPlayersReady";

                    public class PlayerInfo
                    {
                    public int numberID;

                    public string nickname;

                    public int integral;

                    public int portrait;

                    public int seat;

                    public string cardIds;

                    public string battleCardGroup;

                    }

                    public List<PlayerInfo> playerInfoList;

                    public int randomSeed;

                    public int keyFrameRange;

                    public int clientStartDelay;

                    public int battleID;


        }
        public class OnGameOver
        {
                    public static string InterfaceName = "onGameOver";

                    public class PlayerResult
                    {
                    public int numberID;

                    public int changeIntegral;

                    public int currentIntegral;

                    public int currentGrade;

                    public int getGold;

                    public int getBoxId;

                    public int boxSeat;

                    public int gameResult;

                    }

                    public string fightAreaName;

                    public List<PlayerResult> playersResult;


        }
        public class OnAdd
        {
                    public static string InterfaceName = "onAdd";

                    public int numberID;


        }
        public class OnLeave
        {
                    public static string InterfaceName = "onLeave";

                    public int numberID;


        }
        public class OnMatched
        {
                    public static string InterfaceName = "onMatched";

                    public string fightAreaName;


        }
        public class OnMainStateChanged
        {
                    public static string InterfaceName = "onMainStateChanged";

                    public int friendNumberID;

                    public int mainState;


        }
        public class OnChat
        {
                    public static string InterfaceName = "onChat";

                    public string content;

                    public int from;


        }
        public class OnAddedFriend
        {
                    public static string InterfaceName = "onAddedFriend";

                    public int friendNumberID;

                    public string friendNickname;

                    public string friendPortrait;

                    public int friendRelationState;


        }
        public class OnReceiveAddFriendInvitation
        {
                    public static string InterfaceName = "onReceiveAddFriendInvitation";

                    public int inviterNumberID;

                    public string inviterNickname;

                    public int inviterPortrait;


        }
        public class OnReceiveReplyAddFriendInvitation
        {
                    public static string InterfaceName = "onReceiveReplyAddFriendInvitation";

                    public int inviteeNumberID;

                    public string inviteeNickname;

                    public int inviteePortrait;

                    public int isAgree;


        }
        public class OnReceiveFriendGameInvitation
        {
                    public static string InterfaceName = "onReceiveFriendGameInvitation";

                    public int inviterNumberID;


        }
        public class OnReceiveCancelFriendGameInvitation
        {
                    public static string InterfaceName = "onReceiveCancelFriendGameInvitation";


        }
        public class OnReceiveFinishVirusRecruit
        {
                    public static string InterfaceName = "onReceiveFinishVirusRecruit";

                    public int isFinish;

                    public int virusCount;


        }

    }

}
