// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SkillGenerator tool
//      Version: 1.0.0.0

//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

using Util;
using System.Collections;
using System.Collections.Generic;
namespace WG
{
   public class SkillTripleHit : SkillBase
   {
       public int ContinueAttackTimes;
        private static string _dataPath = "StaticData/SDSkillType/SkillTripleHit";
       private static Dictionary<string,SkillTripleHit> _data = new Dictionary<string,SkillTripleHit>();
       private static List<SkillTripleHit> _dataList = new List<SkillTripleHit>();
       public static List<SkillTripleHit> GetDataList()
       {
           return _dataList;
       }

       public override void LoadData()
       {
           string json = StaticDataLoader.GetText(_dataPath);
           List<SkillTripleHit> dataList = LitJson.JsonMapper.ToObject<List<SkillTripleHit>>(json);
           for(int i = 0; i < dataList.Count; i++)
           {
               _data.Add(dataList[i].Id, dataList[i]);
               _dataList.Add(dataList[i]);
           }
       }

       public override void Clear()
       {
           base.Clear();
           _dataList.Clear();
           _data.Clear();
       }

        public static SkillTripleHit GetElement(string id)
       {
            SkillTripleHit val = null;
            _data.TryGetValue(id, out val);
            return val;
       }
   }
}
