// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SkillGenerator tool
//      Version: 1.0.0.0

//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

using Util;
using System.Collections;
using System.Collections.Generic;
namespace WG
{
   public class SkillDot : SkillBase
   {
       public int IntervalTime;
       public string CallSkill;
       public int ContinueTime;
       public string ContinueTimeRead;
       public string IntervalTimeRead;
       public string DamageRead;
        private static string _dataPath = "StaticData/SDSkillType/SkillDot";
       private static Dictionary<string,SkillDot> _data = new Dictionary<string,SkillDot>();
       private static List<SkillDot> _dataList = new List<SkillDot>();
       public static List<SkillDot> GetDataList()
       {
           return _dataList;
       }

       public override void LoadData()
       {
           string json = StaticDataLoader.GetText(_dataPath);
           List<SkillDot> dataList = LitJson.JsonMapper.ToObject<List<SkillDot>>(json);
           for(int i = 0; i < dataList.Count; i++)
           {
               _data.Add(dataList[i].Id, dataList[i]);
               _dataList.Add(dataList[i]);
           }
       }

       public override void Clear()
       {
           base.Clear();
           _dataList.Clear();
           _data.Clear();
       }

        public static SkillDot GetElement(string id)
       {
            SkillDot val = null;
            _data.TryGetValue(id, out val);
            return val;
       }
   }
}
