// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SkillGenerator tool
//      Version: 1.0.0.0

//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

using Util;
using System.Collections;
using System.Collections.Generic;
namespace WG
{
   public class SkillProperty : SkillBase
   {
       public int AttackValue;
       public int AttackPercent;
       public int ArmorValue;
       public int AttackSpeedPercent;
       public int MoveSpeedPercent;
       public int HpRecoveryValue;
       public int HpRecoveryPercent;
       public int ContinueTime;
       public string AddBuffId;
       public int SuckBloodRate;
       public int DodgeRate;
       public int HitRate;
       public int AdditionAttackPercent;
       public int ContinueAttackTimes;
       public int CanOverlay;
       public string ContinueTimeRead;
       public string DodgeNumEffect;
       public string AttackSpeedAbs;
       public string AttackPercentAbs;
       public string DamageValue;
        private static string _dataPath = "StaticData/SDSkillType/SkillProperty";
       private static Dictionary<string,SkillProperty> _data = new Dictionary<string,SkillProperty>();
       private static List<SkillProperty> _dataList = new List<SkillProperty>();
       public static List<SkillProperty> GetDataList()
       {
           return _dataList;
       }

       public override void LoadData()
       {
           string json = StaticDataLoader.GetText(_dataPath);
           List<SkillProperty> dataList = LitJson.JsonMapper.ToObject<List<SkillProperty>>(json);
           for(int i = 0; i < dataList.Count; i++)
           {
               _data.Add(dataList[i].Id, dataList[i]);
               _dataList.Add(dataList[i]);
           }
       }

       public override void Clear()
       {
           base.Clear();
           _dataList.Clear();
           _data.Clear();
       }

        public static SkillProperty GetElement(string id)
       {
            SkillProperty val = null;
            _data.TryGetValue(id, out val);
            return val;
       }
   }
}
