// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SkillGenerator tool
//      Version: 1.0.0.0

//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

using Util;
using System.Collections;
using System.Collections.Generic;
namespace WG
{
   public class SkillMultiAttack : SkillBase
   {
       public string ExtralBulletID;
       public int ExtralBulletTime;
        private static string _dataPath = "StaticData/SDSkillType/SkillMultiAttack";
       private static Dictionary<string,SkillMultiAttack> _data = new Dictionary<string,SkillMultiAttack>();
       private static List<SkillMultiAttack> _dataList = new List<SkillMultiAttack>();
       public static List<SkillMultiAttack> GetDataList()
       {
           return _dataList;
       }

       public override void LoadData()
       {
           string json = StaticDataLoader.GetText(_dataPath);
           List<SkillMultiAttack> dataList = LitJson.JsonMapper.ToObject<List<SkillMultiAttack>>(json);
           for(int i = 0; i < dataList.Count; i++)
           {
               _data.Add(dataList[i].Id, dataList[i]);
               _dataList.Add(dataList[i]);
           }
       }

       public override void Clear()
       {
           base.Clear();
           _dataList.Clear();
           _data.Clear();
       }

        public static SkillMultiAttack GetElement(string id)
       {
            SkillMultiAttack val = null;
            _data.TryGetValue(id, out val);
            return val;
       }
   }
}
