// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SkillGenerator tool
//      Version: 1.0.0.0

//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

using Util;
using System.Collections;
using System.Collections.Generic;
namespace WG
{
   public class SkillBounty : SkillBase
   {
       public FixedNum BountyMultiple;
       public int BountyMultipleRead;
        private static string _dataPath = "StaticData/SDSkillType/SkillBounty";
       private static Dictionary<string,SkillBounty> _data = new Dictionary<string,SkillBounty>();
       private static List<SkillBounty> _dataList = new List<SkillBounty>();
       public static List<SkillBounty> GetDataList()
       {
           return _dataList;
       }

       public override void LoadData()
       {
           string json = StaticDataLoader.GetText(_dataPath);
           List<SkillBounty> dataList = LitJson.JsonMapper.ToObject<List<SkillBounty>>(json);
           for(int i = 0; i < dataList.Count; i++)
           {
               _data.Add(dataList[i].Id, dataList[i]);
               _dataList.Add(dataList[i]);
           }
       }

       public override void Clear()
       {
           base.Clear();
           _dataList.Clear();
           _data.Clear();
       }

        public static SkillBounty GetElement(string id)
       {
            SkillBounty val = null;
            _data.TryGetValue(id, out val);
            return val;
       }
   }
}
