// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SkillGenerator tool
//      Version: 1.0.0.0

//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

using Util;
using System.Collections;
using System.Collections.Generic;
namespace WG
{
   public class SkillManaAbsorb : SkillBase
   {
       public int ManaAbsorb;
       public int PhantasmDamage;
       public int PhantasmMana;
        private static string _dataPath = "StaticData/SDSkillType/SkillManaAbsorb";
       private static Dictionary<string,SkillManaAbsorb> _data = new Dictionary<string,SkillManaAbsorb>();
       private static List<SkillManaAbsorb> _dataList = new List<SkillManaAbsorb>();
       public static List<SkillManaAbsorb> GetDataList()
       {
           return _dataList;
       }

       public override void LoadData()
       {
           string json = StaticDataLoader.GetText(_dataPath);
           List<SkillManaAbsorb> dataList = LitJson.JsonMapper.ToObject<List<SkillManaAbsorb>>(json);
           for(int i = 0; i < dataList.Count; i++)
           {
               _data.Add(dataList[i].Id, dataList[i]);
               _dataList.Add(dataList[i]);
           }
       }

       public override void Clear()
       {
           base.Clear();
           _dataList.Clear();
           _data.Clear();
       }

        public static SkillManaAbsorb GetElement(string id)
       {
            SkillManaAbsorb val = null;
            _data.TryGetValue(id, out val);
            return val;
       }
   }
}
