// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SkillGenerator tool
//      Version: 1.0.0.0

//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

using Util;
using System.Collections;
using System.Collections.Generic;
namespace WG
{
   public class SkillTeam : SkillBase
   {
       public int MemberCount;
       public string ExtralSkillID;
        private static string _dataPath = "StaticData/SDSkillType/SkillTeam";
       private static Dictionary<string,SkillTeam> _data = new Dictionary<string,SkillTeam>();
       private static List<SkillTeam> _dataList = new List<SkillTeam>();
       public static List<SkillTeam> GetDataList()
       {
           return _dataList;
       }

       public override void LoadData()
       {
           string json = StaticDataLoader.GetText(_dataPath);
           List<SkillTeam> dataList = LitJson.JsonMapper.ToObject<List<SkillTeam>>(json);
           for(int i = 0; i < dataList.Count; i++)
           {
               _data.Add(dataList[i].Id, dataList[i]);
               _dataList.Add(dataList[i]);
           }
       }

       public override void Clear()
       {
           base.Clear();
           _dataList.Clear();
           _data.Clear();
       }

        public static SkillTeam GetElement(string id)
       {
            SkillTeam val = null;
            _data.TryGetValue(id, out val);
            return val;
       }
   }
}
