// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SkillGenerator tool
//      Version: 1.0.0.0

//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

using Util;
using System.Collections;
using System.Collections.Generic;
namespace WG
{
   public class SkillBase : StaticDataBase
   {
       public string Id;
       public string level;
       public string Icon;
       public string Name;
       public string Description;
       public int TargetSelectLogic;
       public int Target;
       public List<string> TargetType;
       public string TargetSpecies;
       public int ReleaseRange;
       public int TargetRange;
       public int TargetAngle;
       public int TargetCount;
       public string SkillAnim;
       public int SkillActionTime;
       public List<string> SpellEffect_id;
       public string TargetEffectId;
       public string RegionEffectId;
       public int MagicCost;
       public int TriggerCondition;
       public List<int> TriggerParam;
       public string AddtionSkillId;
       public string BulletId;
       public int IsIgnoreMagicImmune;
       public int CanDodge;
       public string GroupId;
       public int Priority;
       public string SkillType;
        private static string _dataPath = "StaticData/SkillBase";
       private static Dictionary<string,SkillBase> _data = new Dictionary<string,SkillBase>();
       private static List<SkillBase> _dataList = new List<SkillBase>();
       public static List<SkillBase> GetDataList()
       {
           return _dataList;
       }

       public override void LoadData()
       {
           string json = StaticDataLoader.GetText(_dataPath);
           List<SkillBase> dataList = LitJson.JsonMapper.ToObject<List<SkillBase>>(json);
           for(int i = 0; i < dataList.Count; i++)
           {
               _data.Add(dataList[i].Id, dataList[i]);
               _dataList.Add(dataList[i]);
           }
       }

       public override void Clear()
       {
           base.Clear();
           _dataList.Clear();
           _data.Clear();
       }

        public static SkillBase GetElement(string id)
       {
            SkillBase val = null;
            _data.TryGetValue(id, out val);
            return val;
       }
   }
}
