// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SkillGenerator tool
//      Version: 1.0.0.0

//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

using Util;
using System.Collections;
using System.Collections.Generic;
namespace WG
{
   public class SkillDamage : SkillBase
   {
       public int DamageValue;
       public string DamageType;
       public int AttackPercent;
       public int EnemyHpBelow;
       public int TargetLoseHpPercent;
       public int MaxExtraDamage;
        private static string _dataPath = "StaticData/SDSkillType/SkillDamage";
       private static Dictionary<string,SkillDamage> _data = new Dictionary<string,SkillDamage>();
       private static List<SkillDamage> _dataList = new List<SkillDamage>();
       public static List<SkillDamage> GetDataList()
       {
           return _dataList;
       }

       public override void LoadData()
       {
           string json = StaticDataLoader.GetText(_dataPath);
           List<SkillDamage> dataList = LitJson.JsonMapper.ToObject<List<SkillDamage>>(json);
           for(int i = 0; i < dataList.Count; i++)
           {
               _data.Add(dataList[i].Id, dataList[i]);
               _dataList.Add(dataList[i]);
           }
       }

       public override void Clear()
       {
           base.Clear();
           _dataList.Clear();
           _data.Clear();
       }

        public static SkillDamage GetElement(string id)
       {
            SkillDamage val = null;
            _data.TryGetValue(id, out val);
            return val;
       }
   }
}
