// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SkillGenerator tool
//      Version: 1.0.0.0

//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

using Util;
using System.Collections;
using System.Collections.Generic;
namespace WG
{
   public class SkillRebirth : SkillBase
   {
       public int ContinueTime;
       public int Invincible;
       public int DelayTime;
       public string RebornEffectID;
       public string DeathEffectID;
       public string ContinueTimeRead;
        private static string _dataPath = "StaticData/SDSkillType/SkillRebirth";
       private static Dictionary<string,SkillRebirth> _data = new Dictionary<string,SkillRebirth>();
       private static List<SkillRebirth> _dataList = new List<SkillRebirth>();
       public static List<SkillRebirth> GetDataList()
       {
           return _dataList;
       }

       public override void LoadData()
       {
           string json = StaticDataLoader.GetText(_dataPath);
           List<SkillRebirth> dataList = LitJson.JsonMapper.ToObject<List<SkillRebirth>>(json);
           for(int i = 0; i < dataList.Count; i++)
           {
               _data.Add(dataList[i].Id, dataList[i]);
               _dataList.Add(dataList[i]);
           }
       }

       public override void Clear()
       {
           base.Clear();
           _dataList.Clear();
           _data.Clear();
       }

        public static SkillRebirth GetElement(string id)
       {
            SkillRebirth val = null;
            _data.TryGetValue(id, out val);
            return val;
       }
   }
}
