// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SkillGenerator tool
//      Version: 1.0.0.0

//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

using Util;
using System.Collections;
using System.Collections.Generic;
namespace WG
{
   public class SkillMagicImmune : SkillBase
   {
       public int ContinueTime;
       public string ContinueTimeRead;
        private static string _dataPath = "StaticData/SDSkillType/SkillMagicImmune";
       private static Dictionary<string,SkillMagicImmune> _data = new Dictionary<string,SkillMagicImmune>();
       private static List<SkillMagicImmune> _dataList = new List<SkillMagicImmune>();
       public static List<SkillMagicImmune> GetDataList()
       {
           return _dataList;
       }

       public override void LoadData()
       {
           string json = StaticDataLoader.GetText(_dataPath);
           List<SkillMagicImmune> dataList = LitJson.JsonMapper.ToObject<List<SkillMagicImmune>>(json);
           for(int i = 0; i < dataList.Count; i++)
           {
               _data.Add(dataList[i].Id, dataList[i]);
               _dataList.Add(dataList[i]);
           }
       }

       public override void Clear()
       {
           base.Clear();
           _dataList.Clear();
           _data.Clear();
       }

        public static SkillMagicImmune GetElement(string id)
       {
            SkillMagicImmune val = null;
            _data.TryGetValue(id, out val);
            return val;
       }
   }
}
