// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SkillGenerator tool
//      Version: 1.0.0.0

//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

using Util;
using System.Collections;
using System.Collections.Generic;
namespace WG
{
   public class SkillPhantom : SkillBase
   {
       public int PhantomCount;
       public int AttackPercent;
       public int HitPercent;
       public int ContinueTime;
       public int ContinueTimeRead;
       public string BirthEffect;
       public string DeathEffect;
       public int Invincible;
        private static string _dataPath = "StaticData/SDSkillType/SkillPhantom";
       private static Dictionary<string,SkillPhantom> _data = new Dictionary<string,SkillPhantom>();
       private static List<SkillPhantom> _dataList = new List<SkillPhantom>();
       public static List<SkillPhantom> GetDataList()
       {
           return _dataList;
       }

       public override void LoadData()
       {
           string json = StaticDataLoader.GetText(_dataPath);
           List<SkillPhantom> dataList = LitJson.JsonMapper.ToObject<List<SkillPhantom>>(json);
           for(int i = 0; i < dataList.Count; i++)
           {
               _data.Add(dataList[i].Id, dataList[i]);
               _dataList.Add(dataList[i]);
           }
       }

       public override void Clear()
       {
           base.Clear();
           _dataList.Clear();
           _data.Clear();
       }

        public static SkillPhantom GetElement(string id)
       {
            SkillPhantom val = null;
            _data.TryGetValue(id, out val);
            return val;
       }
   }
}
