// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SkillGenerator tool
//      Version: 1.0.0.0

//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

using Util;
using System.Collections;
using System.Collections.Generic;
namespace WG
{
   public class SkillBlink : SkillBase
   {
       public string BlinkEffectID;
        private static string _dataPath = "StaticData/SDSkillType/SkillBlink";
       private static Dictionary<string,SkillBlink> _data = new Dictionary<string,SkillBlink>();
       private static List<SkillBlink> _dataList = new List<SkillBlink>();
       public static List<SkillBlink> GetDataList()
       {
           return _dataList;
       }

       public override void LoadData()
       {
           string json = StaticDataLoader.GetText(_dataPath);
           List<SkillBlink> dataList = LitJson.JsonMapper.ToObject<List<SkillBlink>>(json);
           for(int i = 0; i < dataList.Count; i++)
           {
               _data.Add(dataList[i].Id, dataList[i]);
               _dataList.Add(dataList[i]);
           }
       }

       public override void Clear()
       {
           base.Clear();
           _dataList.Clear();
           _data.Clear();
       }

        public static SkillBlink GetElement(string id)
       {
            SkillBlink val = null;
            _data.TryGetValue(id, out val);
            return val;
       }
   }
}
