// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SkillGenerator tool
//      Version: 1.0.0.0

//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

using Util;
using System.Collections;
using System.Collections.Generic;
namespace WG
{
   public class SkillSputter : SkillBase
   {
       public int SputterRange;
       public int MaxEnemyCount;
       public int DamageValue;
       public string DamageType;
       public int AttackDamagePercent;
        private static string _dataPath = "StaticData/SDSkillType/SkillSputter";
       private static Dictionary<string,SkillSputter> _data = new Dictionary<string,SkillSputter>();
       private static List<SkillSputter> _dataList = new List<SkillSputter>();
       public static List<SkillSputter> GetDataList()
       {
           return _dataList;
       }

       public override void LoadData()
       {
           string json = StaticDataLoader.GetText(_dataPath);
           List<SkillSputter> dataList = LitJson.JsonMapper.ToObject<List<SkillSputter>>(json);
           for(int i = 0; i < dataList.Count; i++)
           {
               _data.Add(dataList[i].Id, dataList[i]);
               _dataList.Add(dataList[i]);
           }
       }

       public override void Clear()
       {
           base.Clear();
           _dataList.Clear();
           _data.Clear();
       }

        public static SkillSputter GetElement(string id)
       {
            SkillSputter val = null;
            _data.TryGetValue(id, out val);
            return val;
       }
   }
}
