// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SkillGenerator tool
//      Version: 1.0.0.0

//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

using Util;
using System.Collections;
using System.Collections.Generic;
namespace WG
{
   public class SkillStun : SkillBase
   {
       public int DamageValue;
       public string DamageType;
       public int StunTime;
       public string AddBuffId;
       public int AttackPercent;
       public string StunTimeRead;
       public string CastFinishedEffect;
       public int Stone;
        private static string _dataPath = "StaticData/SDSkillType/SkillStun";
       private static Dictionary<string,SkillStun> _data = new Dictionary<string,SkillStun>();
       private static List<SkillStun> _dataList = new List<SkillStun>();
       public static List<SkillStun> GetDataList()
       {
           return _dataList;
       }

       public override void LoadData()
       {
           string json = StaticDataLoader.GetText(_dataPath);
           List<SkillStun> dataList = LitJson.JsonMapper.ToObject<List<SkillStun>>(json);
           for(int i = 0; i < dataList.Count; i++)
           {
               _data.Add(dataList[i].Id, dataList[i]);
               _dataList.Add(dataList[i]);
           }
       }

       public override void Clear()
       {
           base.Clear();
           _dataList.Clear();
           _data.Clear();
       }

        public static SkillStun GetElement(string id)
       {
            SkillStun val = null;
            _data.TryGetValue(id, out val);
            return val;
       }
   }
}
