// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SkillGenerator tool
//      Version: 1.0.0.0

//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

using Util;
using System.Collections;
using System.Collections.Generic;
namespace WG
{
   public class SkillParry : SkillBase
   {
       public int ParryProbability;
       public int ParryValue;
       public int ParryPercent;
       public List<string> DamageType;
       public string ParryEffectId;
       public int MaxAbsorbDamage;
       public string AddBuffId;
       public string ParryNumEffect;
        private static string _dataPath = "StaticData/SDSkillType/SkillParry";
       private static Dictionary<string,SkillParry> _data = new Dictionary<string,SkillParry>();
       private static List<SkillParry> _dataList = new List<SkillParry>();
       public static List<SkillParry> GetDataList()
       {
           return _dataList;
       }

       public override void LoadData()
       {
           string json = StaticDataLoader.GetText(_dataPath);
           List<SkillParry> dataList = LitJson.JsonMapper.ToObject<List<SkillParry>>(json);
           for(int i = 0; i < dataList.Count; i++)
           {
               _data.Add(dataList[i].Id, dataList[i]);
               _dataList.Add(dataList[i]);
           }
       }

       public override void Clear()
       {
           base.Clear();
           _dataList.Clear();
           _data.Clear();
       }

        public static SkillParry GetElement(string id)
       {
            SkillParry val = null;
            _data.TryGetValue(id, out val);
            return val;
       }
   }
}
