// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SkillGenerator tool
//      Version: 1.0.0.0

//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

using Util;
using System.Collections;
using System.Collections.Generic;
namespace WG
{
   public class SkillCrit : SkillBase
   {
       public FixedNum Multiple;
       public string MultipleRead;
       public string CritNumEffect;
        private static string _dataPath = "StaticData/SDSkillType/SkillCrit";
       private static Dictionary<string,SkillCrit> _data = new Dictionary<string,SkillCrit>();
       private static List<SkillCrit> _dataList = new List<SkillCrit>();
       public static List<SkillCrit> GetDataList()
       {
           return _dataList;
       }

       public override void LoadData()
       {
           string json = StaticDataLoader.GetText(_dataPath);
           List<SkillCrit> dataList = LitJson.JsonMapper.ToObject<List<SkillCrit>>(json);
           for(int i = 0; i < dataList.Count; i++)
           {
               _data.Add(dataList[i].Id, dataList[i]);
               _dataList.Add(dataList[i]);
           }
       }

       public override void Clear()
       {
           base.Clear();
           _dataList.Clear();
           _data.Clear();
       }

        public static SkillCrit GetElement(string id)
       {
            SkillCrit val = null;
            _data.TryGetValue(id, out val);
            return val;
       }
   }
}
